# Generated by Django 5.1.4 on 2026-10-04 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0017_userprofile_account_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=60, verbose_name='名稱')),
                ('spec', models.JSONField(verbose_name='查詢單')),
                ('shared', models.BooleanField(default=False, verbose_name='全公司共用')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '存起來的報表',
                'verbose_name_plural': '存起來的報表',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'owner', 'name'), name='uniq_saved_report_name')],
            },
        ),
    ]
