# Generated by Django 5.1.4 on 2026-05-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_no', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('in_stock', '在庫'), ('in_transit', '調撥中'), ('sold', '已售'), ('returned', '已退'), ('rma', '維修中'), ('void', '作廢')], default='in_stock', max_length=20)),
                ('purchase_unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='landed cost 攤提後的真實採購單位成本', max_digits=14)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_in', '進貨入庫'), ('sale_out', '銷貨出庫'), ('transfer_out', '調撥出庫'), ('transfer_in', '調撥入庫'), ('return_in', '退貨入庫'), ('adjust', '盤點調整'), ('void', '作廢')], max_length=20)),
                ('ref_doc_type', models.CharField(blank=True, help_text='purchase_order / sales_order / transfer_order …', max_length=40)),
                ('ref_doc_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productserial')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productserial',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='目前位置；sold / void 後可能為 null', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_warehouse_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['serial', '-created_at'], name='inventory_s_serial__ad9e32_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['ref_doc_type', 'ref_doc_id'], name='inventory_s_ref_doc_fb99ff_idx'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['product', 'status'], name='inventory_p_product_a230f3_idx'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['warehouse', 'status'], name='inventory_p_warehou_784a45_idx'),
        ),
        migrations.AddConstraint(
            model_name='productserial',
            constraint=models.UniqueConstraint(fields=('tenant', 'serial_no'), name='uniq_serial_tenant_no'),
        ),
    ]
