# Generated by Django 5.1.4 on 2026-05-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('inventory', '0001_initial'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productserial',
            options={'ordering': ['-id'], 'verbose_name': '商品序號', 'verbose_name_plural': '商品序號'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': '庫存異動', 'verbose_name_plural': '庫存異動'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['code'], 'verbose_name': '倉庫', 'verbose_name_plural': '倉庫'},
        ),
        migrations.AlterField(
            model_name='productserial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='purchase_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='landed cost 攤提後的真實採購單位成本', max_digits=14, verbose_name='採購單位成本'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='進貨時間'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='serial_no',
            field=models.CharField(max_length=80, verbose_name='序號 (IMEI/SN)'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='銷售時間'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='status',
            field=models.CharField(choices=[('in_stock', '在庫'), ('in_transit', '調撥中'), ('sold', '已售'), ('returned', '已退'), ('rma', '維修中'), ('void', '作廢')], default='in_stock', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='目前位置;已售 / 作廢後可能為空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='inventory.warehouse', verbose_name='所在倉庫'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse', verbose_name='來源倉'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', '進貨入庫'), ('sale_out', '銷貨出庫'), ('transfer_out', '調撥出庫'), ('transfer_in', '調撥入庫'), ('return_in', '退貨入庫'), ('adjust', '盤點調整'), ('void', '作廢')], max_length=20, verbose_name='異動類型'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='ref_doc_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='來源單據 ID'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='ref_doc_type',
            field=models.CharField(blank=True, help_text='purchase_order / sales_order / transfer_order ...', max_length=40, verbose_name='來源單據類型'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productserial', verbose_name='序號'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse', verbose_name='目的倉'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.SlugField(max_length=40, verbose_name='倉庫代碼'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=120, verbose_name='倉庫名稱'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
