# Generated by Django 5.1.4 on 2026-05-19 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productserial_purchase_order_item'),
        ('parties', '0008_carrier_next_plan_seq_telecomplan_name_and_more'),
        ('sales', '0009_alter_salesorderpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserial',
            name='acquired_from_member',
            field=models.ForeignKey(blank=True, help_text='從個人會員收購的中古機,記錄賣家;廠商來源留空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acquired_serials', to='parties.customer', verbose_name='收購來源會員'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='acquired_via_sales_order',
            field=models.ForeignKey(blank=True, help_text='個人收購對應的「收購二手」銷貨單(記錄付款給賣家)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acquired_serials', to='sales.salesorder', verbose_name='收購對應銷貨單'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='battery_health',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-100;iOS 機填,Android 機可留空', null=True, verbose_name='電池健康度 (%)'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='condition_grade',
            field=models.CharField(blank=True, choices=[('S', 'S 級 媲美新機 / 拆封未使用'), ('A', 'A 級 95%新以上 幾乎無痕'), ('B', 'B 級 85-95%新 輕微使用痕跡'), ('C', 'C 級 70-85%新 明顯刮痕 功能正常'), ('D', 'D 級 功能有瑕疵或需報備')], default='', help_text='中古機適用,新機留空', max_length=2, verbose_name='成色等級'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='condition_note',
            field=models.CharField(blank=True, help_text='刮痕位置 / 配件齊全度 / 其他特殊狀況', max_length=200, verbose_name='成色備註'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='custom_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='中古機一機一價;銷貨時優先帶這個,空則帶 Product.list_price', max_digits=14, null=True, verbose_name='自定售價'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', '進貨入庫'), ('trade_in', '中古收購入庫'), ('sale_out', '銷貨出庫'), ('transfer_out', '調撥出庫'), ('transfer_in', '調撥入庫'), ('return_in', '退貨入庫'), ('adjust', '盤點調整'), ('void', '作廢')], max_length=20, verbose_name='異動類型'),
        ),
    ]
