# Generated by Django 5.1.4 on 2026-05-19 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_secondhand'),
        ('inventory', '0004_productserial_acquired_from_member_and_more'),
        ('tenants', '0005_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='在庫數量')),
                ('weighted_avg_cost', models.DecimalField(decimal_places=2, default=0, help_text='本倉本商品的加權平均;進貨累計,銷貨/調撥不重算', max_digits=14, verbose_name='加權平均成本(未稅)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '庫存餘額',
                'verbose_name_plural': '庫存餘額',
                'ordering': ['product__sku', 'warehouse__code'],
                'indexes': [models.Index(fields=['tenant', 'product'], name='inventory_s_tenant__2943c1_idx'), models.Index(fields=['tenant', 'warehouse'], name='inventory_s_tenant__a2a9ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'warehouse'), name='uniq_stockbalance_product_warehouse')],
            },
        ),
    ]
