# Generated by Django 5.1.4 on 2026-05-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_secondhand'),
        ('inventory', '0005_stockbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, help_text='配件批量異動填這欄;序號商品由 serial 帶出可留空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_movements', to='catalog.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='qty',
            field=models.PositiveIntegerField(default=1, help_text='序號商品=1;配件=該次批量', verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='serial',
            field=models.ForeignKey(blank=True, help_text='序號商品填這欄;配件批量異動留空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productserial', verbose_name='序號'),
        ),
    ]
