# Generated by Django 5.1.4 on 2026-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productserial_acquired_from_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='電話'),
        ),
    ]
