# Generated by Django 5.1.4 on 2026-05-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_warehouse_address_warehouse_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', '進貨入庫'), ('trade_in', '中古收購入庫'), ('sale_out', '銷貨出庫'), ('transfer_out', '調撥出庫'), ('transfer_in', '調撥入庫'), ('return_in', '退貨入庫'), ('repair_usage', '維修領用'), ('parts_transfer', '零件調貨'), ('adjust', '盤點調整'), ('void', '作廢')], max_length=20, verbose_name='異動類型'),
        ),
    ]
