# Generated by Django 5.1.4 on 2026-07-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockmovement_movement_type'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSerialIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('kind', models.CharField(choices=[('primary_serial', '主序號'), ('imei', 'IMEI'), ('imei2', 'IMEI2'), ('eid', 'EID'), ('sn', 'SN')], max_length=16, verbose_name='類型')),
                ('value', models.CharField(max_length=80, verbose_name='原始值')),
                ('normalized_value', models.CharField(db_index=True, max_length=80, verbose_name='比對鍵')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主識別碼')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='inventory.productserial', verbose_name='商品序號')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '序號識別碼',
                'verbose_name_plural': '序號識別碼',
                'ordering': ['serial', '-is_primary', 'kind'],
                'indexes': [models.Index(fields=['tenant', 'normalized_value'], name='inventory_p_tenant__06f4ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'normalized_value'), name='uniq_serial_identifier_value')],
            },
        ),
    ]
