# Generated by Django 5.1.4 on 2026-10-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productserialidentifier'),
        ('tenants', '0017_userprofile_account_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSerialCodeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('before_imei', models.CharField(blank=True, max_length=80, verbose_name='原 IMEI')),
                ('before_sn', models.CharField(blank=True, max_length=80, verbose_name='原 SN')),
                ('after_imei', models.CharField(blank=True, max_length=80, verbose_name='新 IMEI')),
                ('after_sn', models.CharField(blank=True, max_length=80, verbose_name='新 SN')),
                ('changed_by', models.CharField(blank=True, max_length=150, verbose_name='操作帳號')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_changes', to='inventory.productserial', verbose_name='商品序號')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '序號修改紀錄',
                'verbose_name_plural': '序號修改紀錄',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['serial', '-created_at'], name='inventory_p_serial__b5c651_idx')],
            },
        ),
    ]
