# Generated by Django 5.1.4 on 2026-10-04 14:09

"""作廢的設備不佔碼;主碼多存一份「去掉符號後的值」。

1. `serial_key`:`serial_no` 去掉空白 / 破折號 / 底線 / 點、轉大寫。用碼找設備、檢查碼有沒有被用掉都比這一欄 ——
   同一個碼不管當初寫成 AB12、ab-12 還是 A.B_12 都比得到,不用再猜有哪幾種寫法。這裡替既有的每一台補上。
2. 進貨單打錯整張作廢之後,同一批貨要能用同樣的 IMEI / SN 重新入庫。以前 `serial_no` 在公司內唯一、不看狀態,
   作廢過的碼永遠不能再用。唯一限制改成「不算作廢的」,既有作廢設備在識別碼表裡的登記拿掉
   (作廢的那一筆留著 `serial_no` 當紀錄)。
3. 放掉之後,還在用卻沒登記的設備補登記:以前作廢過的碼不能再用,店員只好加個破折號重新入庫;
   0012 把這兩筆當成同一個碼、只登記到較舊(已作廢)的那一筆。作廢的放掉了,在用的那一台要接手,
   不然別台可以再用同一個碼。

不支援往回退:已經有人用作廢過的碼重新入庫之後,舊的唯一限制(不看狀態)裝不回去。
要回到這支之前的狀態,用升級前的資料庫備份。
"""
import re

from django.db import migrations, models


def _normalize(text):
    return re.sub(r"[\s\-_.]+", "", str(text or "").strip()).upper()


def _looks_like_imei(nv):
    if not (len(nv) == 15 and nv.isascii() and nv.isdigit()):
        return False
    total = 0
    for i, ch in enumerate(reversed(nv)):
        n = int(ch)
        if i % 2 == 1:
            n *= 2
            if n > 9:
                n -= 9
        total += n
    return total % 10 == 0


def fill_keys_and_release_void(apps, schema_editor):
    Serial = apps.get_model("inventory", "ProductSerial")
    Identifier = apps.get_model("inventory", "ProductSerialIdentifier")

    batch = []
    for serial in Serial.objects.only("pk", "serial_no").iterator(chunk_size=2000):
        serial.serial_key = _normalize(serial.serial_no)
        batch.append(serial)
        if len(batch) >= 2000:
            Serial.objects.bulk_update(batch, ["serial_key"])
            batch = []
    if batch:
        Serial.objects.bulk_update(batch, ["serial_key"])

    Identifier.objects.filter(serial__status="void").delete()

    known = set(Identifier.objects.values_list("tenant_id", "normalized_value"))
    has_primary = set(Identifier.objects.filter(is_primary=True).values_list("serial_id", flat=True))
    rows = []
    for pk, tenant_id, serial_no, key in (
        Serial.objects.exclude(status="void")
        .order_by("pk").values_list("pk", "tenant_id", "serial_no", "serial_key")
    ):
        if not key or (tenant_id, key) in known:      # 這個碼已經登記(在它自己或別台身上)
            continue
        known.add((tenant_id, key))
        rows.append(Identifier(
            tenant_id=tenant_id, serial_id=pk, value=serial_no, normalized_value=key,
            kind="imei" if _looks_like_imei(key) else "sn", is_primary=pk not in has_primary,
        ))
    Identifier.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_category_needs_host_model'),
        ('inventory', '0013_main_code_prefers_imei'),
        ('parties', '0015_supplier_is_repair_vendor'),
        ('purchasing', '0007_alter_purchaseorder_tax_method'),
        ('sales', '0016_line_untaxed_tax_return_cost'),
        ('tenants', '0017_userprofile_account_uuid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productserial',
            name='uniq_serial_tenant_no',
        ),
        migrations.AddField(
            model_name='productserial',
            name='serial_key',
            field=models.CharField(blank=True, default='', editable=False, help_text='serial_no 去掉空白 / 破折號 / 底線 / 點、轉大寫;存檔時自動算。用碼找設備、檢查碼有沒有被用掉都比這一欄,不比原文', max_length=80, verbose_name='比對用的主碼'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['tenant', 'serial_key'], name='inventory_p_tenant__782319_idx'),
        ),
        migrations.AddConstraint(
            model_name='productserial',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'void'), _negated=True), fields=('tenant', 'serial_no'), name='uniq_serial_tenant_no'),
        ),
        migrations.RunPython(fill_keys_and_release_void, migrations.RunPython.noop),
    ]
