# Generated by Django 5.1.4 on 2026-07-05 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('source', models.CharField(choices=[('nl_text', '自然語言'), ('purchase_doc', '進貨單(文字/OCR)'), ('voice', '語音轉文字')], default='nl_text', max_length=20, verbose_name='來源')),
                ('raw_input', models.TextField(help_text='使用者餵進來的自然語言或進貨單內容', verbose_name='原始輸入')),
                ('intent_action', models.CharField(blank=True, help_text='解析出的固定動作代碼,如 create_purchase_order', max_length=40, verbose_name='動作')),
                ('parsed_intent', models.JSONField(blank=True, default=dict, help_text='parser 產出的結構化 Intent(未解析成真實主檔前)', verbose_name='解析結果')),
                ('proposal', models.JSONField(blank=True, default=dict, help_text='解析成真實主檔後、可直接執行的 payload + 給人看的顯示內容', verbose_name='提案')),
                ('clarification', models.JSONField(blank=True, default=list, help_text='解析不確定時的追問清單(找不到/對到多筆商品或供應商)', verbose_name='待釐清項目')),
                ('status', models.CharField(choices=[('parsed', '已解析'), ('needs_clarification', '待釐清'), ('awaiting_confirm', '待確認'), ('committed', '已過帳'), ('rejected', '已取消'), ('failed', '失敗')], default='parsed', max_length=24, verbose_name='狀態')),
                ('message', models.CharField(blank=True, help_text='錯誤或提示訊息', max_length=400, verbose_name='訊息')),
                ('result_doc_type', models.CharField(blank=True, help_text='purchase_order / sales_order ...', max_length=40, verbose_name='結果單據類型')),
                ('result_doc_id', models.BigIntegerField(blank=True, null=True, verbose_name='結果單據 ID')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': 'AI 指令紀錄',
                'verbose_name_plural': 'AI 指令紀錄',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='assistant_c_tenant__287788_idx'), models.Index(fields=['result_doc_type', 'result_doc_id'], name='assistant_c_result__c6ba0c_idx')],
            },
        ),
    ]
