# Generated by Django 5.1.4 on 2026-07-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0021_add_default_accessory_brands'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('kind', models.CharField(choices=[('product_sales', '商品銷售需求'), ('repair_part', '維修料件需求')], default='product_sales', max_length=20, verbose_name='標的類型')),
                ('subject_key', models.CharField(max_length=120, verbose_name='標的 key')),
                ('direction', models.CharField(choices=[('up', '需求上升'), ('down', '需求下降'), ('watch', '觀望(熱度升、內部未跟上)')], max_length=10, verbose_name='方向')),
                ('heat_growth', models.DecimalField(decimal_places=4, default=0, help_text='近 7 天 vs 前 7 天;0.28 = +28%', max_digits=8, verbose_name='外部熱度成長')),
                ('internal_growth', models.DecimalField(decimal_places=4, default=0, help_text='商品用 trend_ratio-1;維修用工單成長', max_digits=8, verbose_name='內部領先成長')),
                ('authorized', models.BooleanField(default=False, help_text='外部熱度是否被內部訊號驗證(可否建議加量)', verbose_name='已授權')),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='綜合分數')),
                ('window_end', models.DateField(verbose_name='計算基準日')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='說明')),
                ('status', models.CharField(choices=[('open', '待處理'), ('ack', '已讀'), ('dismissed', '已忽略')], default='open', max_length=12, verbose_name='狀態')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_alerts', to='catalog.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '需求警示',
                'verbose_name_plural': '需求警示',
                'ordering': ['-window_end', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'direction'], name='signals_dem_tenant__0a426c_idx'), models.Index(fields=['tenant', 'kind', 'subject_key'], name='signals_dem_tenant__2cb953_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('source', models.CharField(choices=[('google_trends', 'Google 搜尋趨勢'), ('google_ads', 'Google 關鍵字量'), ('youtube', 'YouTube 討論'), ('supplier_shortage', '供應商缺貨'), ('promo', '促銷活動'), ('repair_search', '維修搜尋'), ('internal_inquiry', '自家詢問'), ('preorder', '預購 / 訂金')], max_length=20, verbose_name='來源')),
                ('subject_key', models.CharField(max_length=120, verbose_name='標的 key')),
                ('period_date', models.DateField(verbose_name='期間(日 / 週起日)')),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='數值')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='附帶資料')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '市場訊號',
                'verbose_name_plural': '市場訊號',
                'ordering': ['-period_date'],
                'indexes': [models.Index(fields=['tenant', 'subject_key', 'period_date'], name='signals_mar_tenant__9706ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source', 'subject_key', 'period_date'), name='uniq_market_signal_point')],
            },
        ),
        migrations.CreateModel(
            name='SubjectAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('alias', models.CharField(max_length=120, verbose_name='別名 / 關鍵字')),
                ('subject_key', models.CharField(max_length=120, verbose_name='標的 key')),
                ('kind', models.CharField(choices=[('product_sales', '商品銷售需求'), ('repair_part', '維修料件需求')], default='product_sales', max_length=20, verbose_name='標的類型')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_aliases', to='catalog.product', verbose_name='對應商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '標的別名',
                'verbose_name_plural': '標的別名',
                'ordering': ['subject_key', 'alias'],
                'indexes': [models.Index(fields=['tenant', 'subject_key'], name='signals_sub_tenant__ce5843_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind', 'alias'), name='uniq_subject_alias')],
            },
        ),
    ]
