# Generated by Django 5.1.4 on 2026-10-10 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0014_void_units_release_codes'),
        ('tenants', '0020_staff_abilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('provider', models.CharField(choices=[('moceo', '膜總裁')], default='moceo', max_length=20, verbose_name='廠商')),
                ('payment_method', models.CharField(default='月結', max_length=20, verbose_name='付款方式')),
                ('delivery_method', models.CharField(default='宅配', max_length=20, verbose_name='取貨方式')),
                ('ship_name', models.CharField(blank=True, default='', max_length=60, verbose_name='收件人')),
                ('ship_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='收件電話')),
                ('ship_address', models.CharField(blank=True, default='', max_length=200, verbose_name='收件地址')),
                ('invoice_type', models.CharField(default='個人', max_length=10, verbose_name='發票')),
                ('buyer_tax_id', models.CharField(blank=True, default='', max_length=20, verbose_name='統一編號')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='發票抬頭')),
                ('invoice_email', models.CharField(blank=True, default='', max_length=200, verbose_name='發票信箱')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_links', to='inventory.warehouse', verbose_name='門市')),
            ],
            options={
                'verbose_name': '叫貨串接',
                'verbose_name_plural': '叫貨串接',
            },
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('provider', models.CharField(choices=[('moceo', '膜總裁')], default='moceo', max_length=20, verbose_name='廠商')),
                ('request_key', models.CharField(max_length=50, verbose_name='畫面的鑰匙')),
                ('vendor_key', models.CharField(max_length=100, verbose_name='送給廠商的鑰匙')),
                ('key_fingerprint', models.CharField(blank=True, default='', max_length=64, verbose_name='送出時的金鑰指紋')),
                ('state', models.CharField(choices=[('sending', '送出中'), ('placed', '已成立'), ('unknown', '不確定')], default='sending', max_length=12, verbose_name='狀況')),
                ('sending_since', models.DateTimeField(blank=True, null=True, verbose_name='開始送出')),
                ('problem', models.CharField(blank=True, default='', max_length=300, verbose_name='不確定的原因')),
                ('vendor_order_no', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='廠商單號')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='廠商算的總額')),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='運費')),
                ('expected_goods', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='叫貨當下的貨款')),
                ('amount_matches', models.BooleanField(blank=True, null=True, verbose_name='金額對得上')),
                ('is_test', models.BooleanField(blank=True, null=True, verbose_name='測試單')),
                ('payment_method', models.CharField(max_length=20, verbose_name='付款方式')),
                ('delivery_method', models.CharField(max_length=20, verbose_name='取貨方式')),
                ('ship_name', models.CharField(blank=True, default='', max_length=60, verbose_name='收件人')),
                ('ship_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='收件電話')),
                ('ship_address', models.CharField(blank=True, default='', max_length=200, verbose_name='收件地址')),
                ('invoice_type', models.CharField(max_length=10, verbose_name='發票')),
                ('buyer_tax_id', models.CharField(blank=True, default='', max_length=20, verbose_name='統一編號')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='發票抬頭')),
                ('invoice_email', models.CharField(blank=True, default='', max_length=200, verbose_name='發票信箱')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='備註')),
                ('vendor_status', models.CharField(blank=True, default='', max_length=40, verbose_name='訂單狀態')),
                ('vendor_payment_status', models.CharField(blank=True, default='', max_length=40, verbose_name='收款狀況')),
                ('vendor_logistics_status', models.CharField(blank=True, default='', max_length=60, verbose_name='物流狀況')),
                ('vendor_shipping_method', models.CharField(blank=True, default='', max_length=40, verbose_name='物流')),
                ('vendor_tracking_no', models.CharField(blank=True, default='', max_length=60, verbose_name='託運單號')),
                ('vendor_ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='廠商收單時間')),
                ('status_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='進度更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='叫貨的人')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendor_orders.vendorlink')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='inventory.warehouse', verbose_name='門市')),
            ],
            options={
                'verbose_name': '叫貨單',
                'verbose_name_plural': '叫貨單',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行號')),
                ('sku', models.CharField(max_length=80, verbose_name='廠商料號')),
                ('spec_id', models.IntegerField(blank=True, null=True, verbose_name='規格編號')),
                ('spec_label', models.CharField(blank=True, default='', max_length=120, verbose_name='規格')),
                ('name', models.CharField(max_length=200, verbose_name='廠商品名')),
                ('unit', models.CharField(blank=True, default='', max_length=10, verbose_name='單位')),
                ('pack_qty', models.PositiveIntegerField(verbose_name='一包幾個')),
                ('packs', models.PositiveIntegerField(verbose_name='包數')),
                ('qty', models.PositiveIntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='叫貨當下的單價')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendor_orders.vendororder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '叫貨明細',
                'verbose_name_plural': '叫貨明細',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('wrapped', models.TextField(verbose_name='加密過的金鑰')),
                ('hint', models.CharField(max_length=20, verbose_name='前幾碼')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='指紋')),
                ('sandbox', models.BooleanField(blank=True, null=True, verbose_name='沙盒金鑰')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret', to='vendor_orders.vendorlink')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '叫貨金鑰',
                'verbose_name_plural': '叫貨金鑰',
            },
        ),
        migrations.AddConstraint(
            model_name='vendorlink',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'warehouse'), name='uniq_vendor_link_store'),
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['tenant', 'warehouse', '-id'], name='vendor_orde_tenant__a359bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendororder',
            constraint=models.UniqueConstraint(fields=('tenant', 'request_key'), name='uniq_vendor_order_request_key'),
        ),
    ]
