# Generated by Django 5.1.4 on 2026-10-10 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_staff_cost'),
        ('inventory', '0014_void_units_release_codes'),
        ('parties', '0016_company_commission'),
        ('purchasing', '0008_billed_qty_zero_is_zero'),
        ('tenants', '0020_staff_abilities'),
        ('vendor_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('request_key', models.CharField(max_length=50, verbose_name='畫面的鑰匙')),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='這一次算進成本的運費')),
            ],
            options={
                'verbose_name': '到貨入庫',
                'verbose_name_plural': '到貨入庫',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendorReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('sku', models.CharField(max_length=80, verbose_name='廠商料號')),
                ('spec_id', models.IntegerField(blank=True, null=True, verbose_name='規格編號')),
                ('is_reissue', models.BooleanField(default=False, verbose_name='瑕疵補發(免費)')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='廠商品名')),
                ('qty', models.PositiveIntegerField(verbose_name='這一次入庫幾個')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='廠商的單價')),
            ],
            options={
                'verbose_name': '到貨入庫明細',
                'verbose_name_plural': '到貨入庫明細',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='vendorlink',
            name='freight_into_cost',
            field=models.BooleanField(default=True, verbose_name='運費算進成本'),
        ),
        migrations.AddField(
            model_name='vendorlink',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.supplier', verbose_name='供應商'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='issue_note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='到貨問題'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='source',
            field=models.CharField(choices=[('pos', '從這裡叫的'), ('outside', '不是從這裡叫的')], default='pos', max_length=10, verbose_name='哪裡叫的'),
        ),
        migrations.AddConstraint(
            model_name='vendororder',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_order_no', ''), _negated=True), fields=('tenant', 'provider', 'vendor_order_no'), name='uniq_vendor_order_no'),
        ),
        migrations.AddField(
            model_name='vendorreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='入庫的人'),
        ),
        migrations.AddField(
            model_name='vendorreceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='vendor_orders.vendororder'),
        ),
        migrations.AddField(
            model_name='vendorreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchasing.purchaseorder', verbose_name='進貨單'),
        ),
        migrations.AddField(
            model_name='vendorreceipt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AddField(
            model_name='vendorreceiptitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='入到哪個品號'),
        ),
        migrations.AddField(
            model_name='vendorreceiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendor_orders.vendorreceipt'),
        ),
        migrations.AddField(
            model_name='vendorreceiptitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AddConstraint(
            model_name='vendorreceipt',
            constraint=models.UniqueConstraint(fields=('tenant', 'request_key'), name='uniq_vendor_receipt_request_key'),
        ),
    ]
