# Generated by Django 5.1.4 on 2026-10-10 11:24

from django.conf import settings
from django.db import migrations, models


def seed_first_vendor(apps, schema_editor):
    """名單的第一筆:膜總裁(現有的串接與叫貨單本來就記代碼 moceo,不用搬)。網址取自原本的設定。已經有就不動。"""
    Vendor = apps.get_model("vendor_orders", "Vendor")
    VendorCategory = apps.get_model("vendor_orders", "VendorCategory")
    if Vendor.objects.filter(code="moceo").exists():
        return
    vendor = Vendor.objects.create(
        code="moceo", name="膜總裁", protocol="standard", key_prefix="mk_live_",
        api_base=getattr(settings, "MOCEO_API_BASE", "https://moceo.mptw-system.com/api/v1"),
    )
    category, _ = VendorCategory.objects.get_or_create(name="保護貼")
    vendor.categories.add(category)


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_orders', '0002_vendorreceipt_vendorreceiptitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '叫貨類別',
                'verbose_name_plural': '叫貨類別',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vendorlink',
            name='clerk_ordering',
            field=models.BooleanField(default=True, verbose_name='店員也可以叫貨'),
        ),
        migrations.AlterField(
            model_name='vendorlink',
            name='provider',
            field=models.CharField(max_length=20, verbose_name='廠商代碼'),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='provider',
            field=models.CharField(max_length=20, verbose_name='廠商代碼'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=40, verbose_name='名稱')),
                ('protocol', models.CharField(choices=[('standard', '全自動(標準格式)')], default='standard', max_length=20, verbose_name='怎麼接')),
                ('api_base', models.CharField(blank=True, default='', max_length=200, verbose_name='對方的網址')),
                ('key_prefix', models.CharField(blank=True, default='', max_length=20, verbose_name='金鑰的開頭')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('categories', models.ManyToManyField(blank=True, related_name='vendors', to='vendor_orders.vendorcategory', verbose_name='類別')),
            ],
            options={
                'verbose_name': '叫貨廠商',
                'verbose_name_plural': '叫貨廠商',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_first_vendor, migrations.RunPython.noop),
    ]
