# Generated by Django 5.1.4 on 2026-10-10 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_orders', '0003_vendor_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='聯絡方式'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='order_email',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='接單信箱'),
        ),
        migrations.AddField(
            model_name='vendorlink',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='開通(半自動的廠商)'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消的時間'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='取消的人'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='manual',
            field=models.BooleanField(default=False, verbose_name='POS 自己成立的(半自動)'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='progress_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='進度備註'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='傳給廠商的時間'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='傳的人'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='sent_how',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='怎麼傳的'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='protocol',
            field=models.CharField(choices=[('standard', '全自動(標準格式)'), ('manual', '半自動(人工傳單)')], default='standard', max_length=20, verbose_name='怎麼接'),
        ),
        migrations.AlterField(
            model_name='vendororderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='叫貨當下的單價'),
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('sku', models.CharField(max_length=80, verbose_name='料號')),
                ('name', models.CharField(max_length=200, verbose_name='品名')),
                ('spec', models.CharField(blank=True, default='', max_length=120, verbose_name='規格')),
                ('kind', models.CharField(blank=True, default='', max_length=40, verbose_name='種類')),
                ('unit', models.CharField(blank=True, default='', max_length=10, verbose_name='單位')),
                ('pack_qty', models.PositiveIntegerField(default=1, verbose_name='一包幾個')),
                ('ref_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='參考單價')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='vendor_orders.vendor', verbose_name='廠商')),
            ],
            options={
                'verbose_name': '廠商價目',
                'verbose_name_plural': '廠商價目',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'sku'), name='uniq_vendor_item_sku')],
            },
        ),
    ]
