# Generated by Django 5.1.4 on 2026-10-06 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_pg_trgm_search'),
        ('tenants', '0017_userprofile_account_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('scope', models.CharField(max_length=40, verbose_name='單據種類')),
                ('key', models.CharField(max_length=64, verbose_name='鑰匙')),
                ('doc_no', models.CharField(blank=True, default='', max_length=40, verbose_name='成立的單號')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='送出的人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '建單鑰匙',
                'verbose_name_plural': '建單鑰匙',
                'indexes': [models.Index(fields=['created_at'], name='core_idempo_created_bb3e28_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'scope', 'key'), name='uniq_idempotency_key')],
            },
        ),
    ]
