# Generated by Django 5.1.4 on 2026-05-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=20, verbose_name='客戶代碼')),
                ('name', models.CharField(max_length=120, verbose_name='客戶名稱')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='電話')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_customer_tenant_code')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=20, verbose_name='供應商代碼')),
                ('name', models.CharField(max_length=120, verbose_name='供應商名稱')),
                ('contact', models.CharField(blank=True, max_length=60, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='電話')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_supplier_tenant_code')],
            },
        ),
    ]
