# Generated by Django 5.1.4 on 2026-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['phone'], 'verbose_name': '會員', 'verbose_name_plural': '會員'},
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_tenant_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=120, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='即會員編號;同租戶內唯一', max_length=40, verbose_name='電話 (會員編號)'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='uniq_customer_tenant_phone'),
        ),
    ]
