# Generated by Django 5.1.4 on 2026-05-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_salesperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['phone'], 'verbose_name': '客戶', 'verbose_name_plural': '客戶'},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_member',
            field=models.BooleanField(default=False, help_text='加入會員制度的客戶(會員為客戶的子類別)', verbose_name='會員'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='電話'),
        ),
    ]
