# Generated by Django 5.1.4 on 2026-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_customer_options_customer_is_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kind',
            field=models.CharField(choices=[('individual', '個人'), ('peer', '同業 / 盤商'), ('corporate', '企業'), ('other', '其他')], default='individual', help_text='客戶來源類型;同業/盤商指其他通訊行批發轉售', max_length=20, verbose_name='客戶類別'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_member',
            field=models.BooleanField(default=False, help_text='加入會員制度的客戶(會員為客戶的子身分,通常用於個人類別)', verbose_name='會員'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=120, verbose_name='姓名 / 名稱'),
        ),
    ]
