# Generated by Django 5.1.4 on 2026-05-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_customer_kind_alter_customer_is_member_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=10, verbose_name='代碼')),
                ('name', models.CharField(max_length=40, verbose_name='名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '電信商',
                'verbose_name_plural': '電信商',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TelecomPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=40, verbose_name='方案代碼')),
                ('monthly_fee', models.PositiveIntegerField(verbose_name='月租')),
                ('contract_months', models.PositiveIntegerField(verbose_name='綁約月數')),
                ('kind', models.CharField(choices=[('new', '新辦'), ('renewal', '續約'), ('portin', '攜碼')], default='new', max_length=10, verbose_name='類型')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='佣金')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='parties.carrier', verbose_name='電信商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '電信方案',
                'verbose_name_plural': '電信方案',
                'ordering': ['carrier__code', 'monthly_fee', 'contract_months', 'kind'],
            },
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_carrier_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='telecomplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_telecomplan_tenant_code'),
        ),
    ]
