# Generated by Django 5.1.4 on 2026-05-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_carrier_telecomplan_carrier_uniq_carrier_tenant_code_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('card_no', models.CharField(max_length=25, verbose_name='卡號 (ICCID)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, help_text='廠商收取的押金;開通後或還卡時歸還', max_digits=14, verbose_name='押金')),
                ('deposit_refunded', models.BooleanField(default=False, help_text='上線開通或還卡退款後勾選', verbose_name='押金已歸還')),
                ('status', models.CharField(choices=[('in_stock', '在庫'), ('issued', '已出卡'), ('activated', '已開通'), ('returned', '退回廠商'), ('void', '作廢')], default='in_stock', max_length=20, verbose_name='狀態')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='出卡時間')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='開通時間')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='退回時間')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sim_cards', to='parties.carrier', verbose_name='廠商')),
            ],
            options={
                'verbose_name': 'SIM 卡',
                'verbose_name_plural': 'SIM 卡',
                'ordering': ['vendor__code', 'card_no'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'card_no'), name='uniq_simcard_tenant_card_no')],
            },
        ),
    ]
