# Generated by Django 5.1.4 on 2026-05-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_simcard'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='next_plan_seq',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='下一方案流水'),
        ),
        migrations.AddField(
            model_name='telecomplan',
            name='name',
            field=models.CharField(default='', help_text='使用者編排的識別名稱;同租戶內唯一', max_length=120, verbose_name='專案名稱'),
        ),
        migrations.AlterField(
            model_name='telecomplan',
            name='code',
            field=models.SlugField(blank=True, editable=False, help_text='系統自動產生:{電信商代碼}-{6位流水}', max_length=40, verbose_name='方案代碼'),
        ),
        migrations.AddConstraint(
            model_name='telecomplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_telecomplan_tenant_name'),
        ),
    ]
