# Generated by Django 5.1.4 on 2026-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_carrier_next_plan_seq_telecomplan_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': '供應商', 'verbose_name_plural': '供應商'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, help_text='數字小的排前面;常用供應商往前調方便快速點選', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.SlugField(blank=True, editable=False, help_text='系統自動產生:S-{6位流水};前端不輸入', max_length=20, verbose_name='供應商代碼'),
        ),
    ]
