# Generated by Django 5.1.4 on 2026-05-23 04:56
#
# 加入 Customer.code (自動產生編號) + phone 改選填 + 改用 code 作為唯一鍵。
# 既有客戶以 phone 排序回填 C-00001 起,並推進 tenant.next_customer_seq。

from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    Customer = apps.get_model("parties", "Customer")
    Tenant = apps.get_model("tenants", "Tenant")

    for tenant in Tenant.objects.all():
        customers = list(
            Customer.objects.filter(tenant=tenant).order_by("phone", "pk")
        )
        if not customers:
            continue
        for idx, c in enumerate(customers, start=1):
            Customer.objects.filter(pk=c.pk).update(code=f"C-{idx:05d}")
        tenant.next_customer_seq = len(customers) + 1
        tenant.save(update_fields=["next_customer_seq"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_renumber_existing_suppliers'),
        ('tenants', '0007_tenant_next_customer_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['code'], 'verbose_name': '客戶', 'verbose_name_plural': '客戶'},
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_tenant_phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.SlugField(blank=True, editable=False, help_text='系統自動產生:C-{5位流水};前端不顯示也不輸入', max_length=20, verbose_name='客戶編號'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='電話'),
        ),
        migrations.RunPython(backfill_codes, noop),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_customer_tenant_code'),
        ),
    ]
