# Generated by Django 5.1.4 on 2026-05-26 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0013_remove_customer_is_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(blank=True, help_text='綁定後該帳號操作時,表單經手人自動預設帶此業務員', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person', to=settings.AUTH_USER_MODEL, verbose_name='登入帳號'),
        ),
    ]
