# Generated by Django 5.1.4 on 2026-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0015_supplier_is_repair_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomplan',
            name='company_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='公司實際拿的佣金;只有管理員看得到。空的 = 還沒設定', max_digits=14, null=True, verbose_name='公司佣金'),
        ),
        migrations.AlterField(
            model_name='telecomplan',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='業務員佣金'),
        ),
    ]
