# Generated by Django 5.1.4 on 2026-05-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='作為 SKU 前綴；建議 2-4 個大寫英數，例如 PH（手機）、TB（平板）、AC（配件）', max_length=8)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('next_sku_seq', models.PositiveIntegerField(default=1, editable=False, help_text='下一個要發出的流水號；每次發 SKU 後 +1')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(editable=False, help_text='系統自動產生：{category.code}-{6位流水}', max_length=60)),
                ('name', models.CharField(help_text='使用者編排的商品名稱，建議含規格（例：iPhone 15 Pro 256GB 黑）', max_length=200)),
                ('spec', models.CharField(blank=True, help_text='補充規格描述，不參與唯一性', max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('weighted_avg_cost', models.DecimalField(decimal_places=2, default=0, help_text='當下加權平均成本；每次進貨過帳時重算', max_digits=14)),
                ('list_price', models.DecimalField(decimal_places=2, default=0, help_text='標準零售價', max_digits=14)),
                ('requires_serial', models.BooleanField(default=True, help_text='是否逐台追蹤序號；3C 預設 True')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_category_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_category_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_pro_tenant__e1f8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='catalog_pro_barcode_58f8f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='uniq_product_tenant_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_product_tenant_name'),
        ),
    ]
