# Generated by Django 5.1.4 on 2026-05-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': '商品類別', 'verbose_name_plural': '商品類別'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.SlugField(help_text='作為 SKU 前綴；建議 2-4 個大寫英數,例如 PH(手機)、TB(平板)、AC(配件)', max_length=8, verbose_name='類別代碼'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, verbose_name='類別名稱'),
        ),
        migrations.AlterField(
            model_name='category',
            name='next_sku_seq',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='下一個要發出的流水號;每次發 SKU 後 +1', verbose_name='下一流水號'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=80, verbose_name='條碼'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用'),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='建議零售價'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='使用者編排的商品名稱,建議含規格(例:iPhone 15 Pro 256GB 黑)', max_length=200, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_serial',
            field=models.BooleanField(default=True, help_text='是否逐台追蹤序號;3C 預設 True', verbose_name='需追蹤序號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(editable=False, help_text='系統自動產生:{類別代碼}-{6位流水}', max_length=60, verbose_name='品號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec',
            field=models.CharField(blank=True, help_text='補充規格描述,不參與唯一性', max_length=200, verbose_name='規格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weighted_avg_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='當下加權平均成本;每次進貨過帳時重算', max_digits=14, verbose_name='加權平均成本'),
        ),
    ]
