# Generated by Django 5.1.4 on 2026-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allows_commission',
            field=models.BooleanField(default=False, help_text='銷貨時是否露出佣金欄位', verbose_name='可有業務員佣金'),
        ),
        migrations.AddField(
            model_name='product',
            name='allows_telecom_line',
            field=models.BooleanField(default=False, help_text='銷貨時是否露出 SIM 卡 / 門號 / 促銷方案 / 上線日 欄位', verbose_name='可綁門號合約'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_serial',
            field=models.BooleanField(default=True, help_text='是否逐台追蹤序號(IMEI/SN);手機/平板=True,配件=False', verbose_name='需追蹤序號'),
        ),
    ]
