# Generated by Django 5.1.4 on 2026-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_allows_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counts_cash',
            field=models.BooleanField(default=True, help_text='該品號金額是否計入現金流量', verbose_name='計入現金'),
        ),
        migrations.AddField(
            model_name='product',
            name='counts_margin',
            field=models.BooleanField(default=True, help_text='該品號金額是否計入毛利報表', verbose_name='計入毛利'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='無實體商品(手續費 / 折抵 / 成本回補等);銷貨時不扣庫存、不建 IMEI、不寫異動', verbose_name='虛擬商品'),
        ),
    ]
