# Generated by Django 5.1.4 on 2026-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_counts_cash_product_counts_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_secondhand',
            field=models.BooleanField(default=False, help_text='中古機主檔,序號需逐隻記成色 / 電池 / 售價 / 備註,銷貨單價以序號自定為準', verbose_name='中古機'),
        ),
    ]
