# Generated by Django 5.1.4 on 2026-05-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_is_secondhand_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.PositiveIntegerField(default=0, help_text='跨倉總庫存低於此數時,首頁會跳警示。0 = 不提醒', verbose_name='安全庫存'),
        ),
    ]
