# Generated by Django 5.1.4 on 2026-05-28 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_safety_stock'),
        ('tenants', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', '主力現貨'), ('replacing', '即將換代'), ('discontinued', '停產下架'), ('clearance', '清倉處理')], default='active', help_text='影響庫存警示行為:active=主力現貨,低庫存會跳補貨警示;replacing=即將換代,低庫存改顯示審查提醒;discontinued/clearance=停產/清倉,不觸發補貨警示', max_length=16, verbose_name='商品狀態'),
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('accessory_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_relations', to='catalog.product', verbose_name='配件商品')),
                ('host_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_relations', to='catalog.product', verbose_name='主機商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '商品關聯',
                'verbose_name_plural': '商品關聯',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'host_product', 'accessory_product'), name='uniq_product_relation'), models.CheckConstraint(condition=models.Q(('host_product', models.F('accessory_product')), _negated=True), name='product_relation_not_self')],
            },
        ),
    ]
