# Generated by Django 5.1.4 on 2026-05-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_lifecycle_status_productrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_type',
            field=models.CharField(choices=[('none', '非配件'), ('phone_specific', '機型專屬'), ('universal', '通用型')], default='none', help_text='機型專屬:安全庫存改用動態公式(主機日均×購買率×補貨天數);通用型:用 safety_stock 靜態欄位;非配件:商品本身是主機', max_length=16, verbose_name='配件類型'),
        ),
        migrations.AddField(
            model_name='product',
            name='attach_rate',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='預估買主機的人有多少比例會買此配件(0.0~1.0,預設 0.30)', max_digits=4, verbose_name='配件購買率'),
        ),
        migrations.AddField(
            model_name='product',
            name='replenish_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='動態安全庫存的天數因子(下次補貨能撐幾天),預設 14', verbose_name='補貨天數'),
        ),
    ]
