# Generated by Django 5.1.4 on 2026-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_accessory_type_product_attach_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('vivo', 'VIVO'), ('oppo', 'OPPO'), ('xiaomi', '小米'), ('asus', 'ASUS'), ('google', 'Google'), ('sony', 'Sony'), ('other', '其他')], default='', help_text='僅主機需填(手機/平板品牌)', max_length=16, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='generation',
            field=models.PositiveIntegerField(blank=True, help_text='系統會從品名末碼自動帶數字,可手動修正', null=True, verbose_name='世代序號'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_variant',
            field=models.BooleanField(default=False, help_text='勾選代表此商品為同代不同容量/顏色的變體,後續系統的『下一代上市自動換代』判斷會略過此筆', verbose_name='規格變體'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, default='', help_text='例:iPhone、Galaxy A 系列、Redmi Note', max_length=64, verbose_name='產品系列'),
        ),
    ]
