# Generated by Django 5.1.4 on 2026-05-28 05:33

import django.db.models.deletion
from django.db import migrations, models


def _compute_key(product):
    """跟 apps.catalog.phone_model.compute_phone_model_key 邏輯一致,
    inline 避免 migration import 主 app 程式造成循環依賴。"""
    import re
    series = (getattr(product, "series", "") or "").strip()
    generation = getattr(product, "generation", None)
    if series:
        name = f"{series} {generation}".strip() if generation else series
    else:
        name = (product.name or "")
        capacity = re.compile(r"\s*\d+\s*(?:G|GB|TB)\b", re.IGNORECASE)
        color = re.compile(
            r"\s*(?:[黑白金銀灰藍紅綠紫粉橙黃青棕褐]+色?"
            r"|Black|White|Gold|Silver|Grey|Gray|Blue|Red|Green|Purple"
            r"|Pink|Orange|Yellow|Bronze|Midnight|Starlight|Graphite|Sierra)\s*$",
            re.IGNORECASE,
        )
        secondhand = re.compile(r"\s*\(?\s*中古\s*\)?\s*$")
        prev = None
        s = name
        while prev != s:
            prev = s
            s = capacity.sub("", s)
            s = color.sub("", s)
            s = secondhand.sub("", s)
            s = re.sub(r"\s*/\s*", " ", s)
            s = re.sub(r"\s+", " ", s).strip()
        name = s
    return name.strip().lower()


def backfill_host_model_key(apps, schema_editor):
    """既有 ProductRelation row 從 host_product 推 host_model_key。
    若推完有重複(同 tenant + 同 key + 同 accessory),保留第一筆,其餘刪除。
    """
    PR = apps.get_model("catalog", "ProductRelation")
    seen = set()
    to_delete = []
    for pr in PR.objects.select_related("host_product").all():
        key = _compute_key(pr.host_product)
        triple = (pr.tenant_id, key, pr.accessory_product_id)
        if triple in seen:
            to_delete.append(pr.id)
            continue
        seen.add(triple)
        pr.host_model_key = key
        pr.save(update_fields=["host_model_key"])
    if to_delete:
        PR.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_brand_product_generation_product_is_variant_and_more'),
        ('tenants', '0012_userprofile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productrelation',
            name='uniq_product_relation',
        ),
        migrations.AddField(
            model_name='productrelation',
            name='host_model_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='lowercase 機型名稱,從 host_product 推導(品名去變體 / series+generation)', max_length=128, verbose_name='機型 key'),
        ),
        migrations.AlterField(
            model_name='productrelation',
            name='host_product',
            field=models.ForeignKey(help_text='該機型的代表 SKU(任一);邏輯比對以 host_model_key 為準', on_delete=django.db.models.deletion.CASCADE, related_name='accessory_relations', to='catalog.product', verbose_name='主機代表 SKU'),
        ),
        # backfill 既有資料的 model_key,再加 unique constraint(順序很重要)
        migrations.RunPython(backfill_host_model_key, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.UniqueConstraint(fields=('tenant', 'host_model_key', 'accessory_product'), name='uniq_product_relation_by_model'),
        ),
    ]
