# Generated by Django 5.1.4 on 2026-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productrelation_host_model_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lifecycle_status',
            field=models.CharField(choices=[('pending', '待補齊'), ('active', '主力現貨'), ('replacing', '即將換代'), ('discontinued', '停產下架'), ('clearance', '清倉處理')], default='active', help_text='影響庫存警示行為:active=主力現貨,低庫存會跳補貨警示;replacing=即將換代,低庫存改顯示審查提醒;discontinued/clearance=停產/清倉,不觸發補貨警示', max_length=16, verbose_name='商品狀態'),
        ),
    ]
