# Generated by Django 5.1.4 on 2026-05-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_lifecycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='零件對同行調貨的標準售價', max_digits=14, verbose_name='對外售價'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_externally_sellable',
            field=models.BooleanField(default=False, help_text='零件可對同行調貨;銷貨單能挑,異動原因標『零件調貨』', verbose_name='可對外銷售'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='防呆下限;銷貨時手動調整不可低於此值', max_digits=14, verbose_name='最低售價'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_type',
            field=models.CharField(choices=[('product', '商品倉'), ('parts', '零件倉')], default='product', help_text='商品倉=銷貨用、安全庫存動態算;零件倉=維修用、靜態安全庫存', max_length=16, verbose_name='倉別'),
        ),
    ]
