# Generated by Django 5.1.4 on 2026-05-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_external_sale_price_and_more'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=80, verbose_name='範本名稱')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '零件範本',
                'verbose_name_plural': '零件範本',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(help_text='例:螢幕總成', max_length=80, verbose_name='零件種類名稱')),
                ('code', models.CharField(help_text='用於組品號的後綴(例:SCR / BAT / BACK)', max_length=10, verbose_name='零件代碼')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('default_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='預設成本')),
                ('default_safety_stock', models.PositiveIntegerField(default=0, verbose_name='預設安全庫存')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.parttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='parttemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_part_template_name'),
        ),
        migrations.AddConstraint(
            model_name='parttemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uniq_part_template_item_code'),
        ),
    ]
