# Generated by Django 5.1.4 on 2026-05-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_add_part_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttemplateitem',
            name='shared_across_models',
            field=models.BooleanField(default=False, help_text='勾選後,此零件在批次建立時不會逐機型展開,而是每個品牌建立一筆共用 SKU,相容多個選定機型。常見於電池等少數可共用的零件;螢幕/後蓋等請保持不勾', verbose_name='跨機型共用'),
        ),
    ]
