# Generated by Django 5.1.4 on 2026-05-28 16:34
"""Phase 1 框架化:加 Brand + PhoneSeries 主檔,Product.brand / series 從 CharField → FK。

舊資料是測試資料 (已告知使用者),這支 migration 不做資料保留,
直接 RemoveField + AddField,舊字串內容會 lost。
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_part_template_item_shared"),
        ("tenants", "0014_add_repair_warranty_unlock_returnvisit"),
    ]

    operations = [
        # ── 1. 建立兩個 master 表
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="建立時間")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新時間")),
                ("code", models.SlugField(max_length=20, verbose_name="代碼")),
                ("name", models.CharField(max_length=80, verbose_name="顯示名稱")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.tenant", verbose_name="租戶")),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PhoneSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="建立時間")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新時間")),
                ("code", models.SlugField(max_length=20, verbose_name="代碼")),
                ("name", models.CharField(max_length=80, verbose_name="顯示名稱")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="series", to="catalog.brand", verbose_name="品牌")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.tenant", verbose_name="租戶")),
            ],
            options={
                "verbose_name": "產品系列",
                "verbose_name_plural": "產品系列",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(fields=("tenant", "code"), name="uniq_brand_tenant_code"),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(fields=("tenant", "name"), name="uniq_brand_tenant_name"),
        ),
        migrations.AddConstraint(
            model_name="phoneseries",
            constraint=models.UniqueConstraint(fields=("tenant", "brand", "code"), name="uniq_phone_series_brand_code"),
        ),

        # ── 2. Product 欄位重組:舊 brand/series CharField 拿掉、加 FK + suffix
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="series",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text="僅主機需填(從品牌主檔挑)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.brand",
                verbose_name="品牌",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text="同品牌底下的系列(從產品系列主檔挑)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.phoneseries",
                verbose_name="產品系列",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model_suffix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="型號的尾段差異化標記;例:Pro / Pro Max / Plus / Ultra / +。拼出完整機型名稱:系列名稱 + 世代 + 後綴",
                max_length=30,
                verbose_name="型號後綴",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="generation",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="同系列第幾代;例:iPhone 15 → 15、Galaxy S26 → 26",
                null=True,
                verbose_name="世代序號",
            ),
        ),
    ]
