# Generated by Django 5.1.4 on 2026-05-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_brand_series_master'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=20, verbose_name='代碼')),
                ('name', models.CharField(max_length=40, verbose_name='顯示名稱')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '產品類型',
                'verbose_name_plural': '產品類型',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='phoneseries',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='catalog.producttype', verbose_name='產品類型'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_product_type_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_product_type_tenant_name'),
        ),
    ]
