# Generated by Django 5.1.4 on 2026-05-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_add_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dynamic_safety_stock',
            field=models.PositiveIntegerField(default=0, help_text='由銷量 / 主機帶動算出的補貨點。0 = 系統判定不需補貨', verbose_name='動態安全庫存'),
        ),
        migrations.AddField(
            model_name='product',
            name='dynamic_stats_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='動態統計更新時間'),
        ),
        migrations.AddField(
            model_name='product',
            name='trend_ratio',
            field=models.DecimalField(decimal_places=2, default=1, help_text='>1.2 銷售回溫;<0.5 銷售退燒;1 表示穩定', max_digits=5, verbose_name='銷售趨勢比'),
        ),
        migrations.AddField(
            model_name='product',
            name='velocity_baseline_90d',
            field=models.DecimalField(decimal_places=3, default=0, help_text='過去 90 天的日均,當做趨勢比較基準', max_digits=10, verbose_name='90 日基準日均'),
        ),
        migrations.AddField(
            model_name='product',
            name='velocity_ewma',
            field=models.DecimalField(decimal_places=3, default=0, help_text='指數加權移動平均(α=0.15)的最新日均銷量', max_digits=10, verbose_name='EWMA 日均銷量'),
        ),
        migrations.AddField(
            model_name='product',
            name='velocity_recent_14d',
            field=models.DecimalField(decimal_places=3, default=0, help_text='最近 14 天的單純日均', max_digits=10, verbose_name='近 14 日均銷量'),
        ),
    ]
