# Generated by Django 5.1.4 on 2026-05-31 12:08

import django.db.models.deletion
from django.db import migrations, models


# 系統建議的 4 個預設狀態 — migration 完成後自動 seed 給每個 active tenant。
# 經銷商可在「庫存 → 商品狀態」自行增刪改。
DEFAULT_CONDITIONS = [
    {"code": "brand-new", "name": "全新", "is_secondhand": False, "sort_order": 1},
    {"code": "opened", "name": "已拆封", "is_secondhand": False, "sort_order": 2},
    {
        "code": "used-warranty",
        "name": "中古機(保固內)",
        "is_secondhand": True,
        "sort_order": 3,
    },
    {"code": "used", "name": "中古機", "is_secondhand": True, "sort_order": 4},
]


def seed_default_conditions(apps, schema_editor):
    """為每個現存 tenant seed 4 個預設狀態。已存在(以 code 比對)的略過。"""
    Tenant = apps.get_model("tenants", "Tenant")
    Condition = apps.get_model("catalog", "Condition")
    for tenant in Tenant.objects.all():
        for spec in DEFAULT_CONDITIONS:
            Condition.objects.get_or_create(
                tenant=tenant,
                code=spec["code"],
                defaults={
                    "name": spec["name"],
                    "is_secondhand": spec["is_secondhand"],
                    "sort_order": spec["sort_order"],
                    "is_active": True,
                },
            )


def unseed_conditions(apps, schema_editor):
    """rollback:把預設的 4 個刪除(經銷商手動加的不動)。"""
    Condition = apps.get_model("catalog", "Condition")
    codes = [c["code"] for c in DEFAULT_CONDITIONS]
    Condition.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_add_dynamic_stock_stats'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=20, verbose_name='代碼')),
                ('name', models.CharField(max_length=40, verbose_name='顯示名稱')),
                ('is_secondhand', models.BooleanField(default=False, help_text='勾選後此狀態下建立的 SKU 自動 is_secondhand=True,觸發中古機成本邏輯(每隻獨立 purchase_unit_cost)', verbose_name='視為中古機')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '商品狀態',
                'verbose_name_plural': '商品狀態',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(blank=True, help_text='全新 / 已拆封 / 中古機(保固內)/ 中古機 …由「新增手機型號」wizard 一鍵帶入;舊資料未指定為 NULL,沿用 is_secondhand 旗標判斷', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.condition', verbose_name='商品狀態'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_condition_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_condition_tenant_name'),
        ),
        migrations.RunPython(seed_default_conditions, reverse_code=unseed_conditions),
    ]
