# Generated by Django 5.1.4 on 2026-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_add_condition_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttemplate',
            name='default_accessory_categories',
            field=models.JSONField(blank=True, default=list, help_text='例:["殼","貼"];線 / 充走通用配件不綁機型,不放這裡', verbose_name='預設配件類別'),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='default_capacities',
            field=models.JSONField(blank=True, default=list, help_text='例:["128GB","256GB","512GB","1TB"];wizard 第 2 步當作預設勾選項', verbose_name='預設容量清單'),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='default_colors',
            field=models.JSONField(blank=True, default=list, help_text='例:["黑","白","鈦原色"];wizard 第 2 步當作預設勾選項', verbose_name='預設顏色清單'),
        ),
    ]
