# Generated by Django 5.1.4 on 2026-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_extend_part_template_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttemplate',
            name='default_accessory_brands',
            field=models.JSONField(blank=True, default=list, help_text='例:["imos","HODA","JTLEGEND"];「+ 新增配件」wizard 套此範本時,會列出這些品牌讓使用者一個個建商品線。純參考用,不直接建 SKU', verbose_name='常用配件品牌'),
        ),
    ]
