# Generated by Django 5.1.4 on 2026-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_add_default_accessory_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, default='', help_text='結構化容量,例:128GB / 256GB / 1TB。用於避免 128G 被誤對成 256G', max_length=20, verbose_name='容量'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', help_text='結構化顏色,例:黑 / 藍 / 原色鈦金屬', max_length=30, verbose_name='顏色'),
        ),
        migrations.AddField(
            model_name='product',
            name='region_version',
            field=models.CharField(blank=True, default='', help_text='例:台版 / 港版 / 美版 / 陸版。不同版本視為不同商品', max_length=30, verbose_name='地區版本'),
        ),
    ]
