# Generated by Django 5.1.4 on 2026-09-15 07:50

import re

import django.db.models.deletion
from django.db import migrations, models


# 舊機型名稱的計算邏輯(凍結版)。migration 不 import apps.catalog.phone_model
# —— 那是會隨業務演進的函式,未來版本下重跑會得到不一樣的結果。
_CAPACITY_RE = re.compile(r"\s*(?:\d+\s*/\s*)*\d+\s*(?:G|GB|TB)\b", re.IGNORECASE)
_EMPTY_PARENS_RE = re.compile(r"[\(\[（［]\s*[\)\]）］]")
_COLOR_RE = re.compile(
    r"\s*(?:"
    r"(?:[一-鿿]{1,3})?[黑白金銀灰藍紅綠紫粉橙黃青棕褐]+色?"
    r"|Black|White|Gold|Silver|Grey|Gray|Blue|Red|Green|Purple"
    r"|Pink|Orange|Yellow|Bronze|Midnight|Starlight|Graphite|Sierra"
    r")\s*$",
    re.IGNORECASE,
)
_SECONDHAND_RE = re.compile(r"\s*\(?\s*中古\s*\)?\s*$")


def _extract_from_name(name):
    s = name or ""
    for _ in range(3):
        before = s
        s = _SECONDHAND_RE.sub("", s)
        s = _COLOR_RE.sub("", s)
        s = _CAPACITY_RE.sub("", s)
        s = _EMPTY_PARENS_RE.sub("", s)
        s = s.strip(" -·、,,")
        if s == before:
            break
    return s.strip()


def _model_name_for_reverse(product, series_name):
    if product.series_id and series_name:
        parts = [series_name]
        if product.generation:
            parts.append(str(product.generation))
        if product.model_suffix:
            parts.append(product.model_suffix)
        out = parts[0]
        for p in parts[1:]:
            if not p:
                continue
            out += p if p[0] in "+/" else " " + p
        return out.strip()
    return _extract_from_name(product.name or "")


def _refill_host_product(apps, schema_editor):
    """退版前把 host_product 為 NULL 的相容關係補回一支代表 SKU。

    補法:同租戶、同機型(先用 host_model,退而求其次用 host_model_key)
    底下任挑一支還活著的商品。整款 SKU 都被刪光時無法無損還原成舊 schema
    —— 那就明白拒絕退版,不會為了讓 migration 過而偷偷刪掉相容關係。
    """
    Product = apps.get_model("catalog", "Product")
    ProductRelation = apps.get_model("catalog", "ProductRelation")
    PhoneSeries = apps.get_model("catalog", "PhoneSeries")

    orphans = list(ProductRelation.objects.filter(host_product__isnull=True))
    if not orphans:
        return

    series_names = dict(PhoneSeries.objects.values_list("id", "name"))
    stuck = []
    for rel in orphans:
        qs = Product.objects.filter(tenant_id=rel.tenant_id)
        sub = (
            qs.filter(phone_model_id=rel.host_model_id)
            if rel.host_model_id
            else qs.none()
        )
        pick = sub.exclude(id=rel.accessory_product_id).first()
        if pick is None and rel.host_model_key:
            # 退路一:同 key 的其他關聯借一支代表 SKU。
            # 一定要排除這一列自己的配件,不然會借到配件本身,
            # 變成 host == accessory 撞 product_relation_not_self。
            sibling = (
                ProductRelation.objects.filter(
                    tenant_id=rel.tenant_id,
                    host_model_key=rel.host_model_key,
                    host_product__isnull=False,
                )
                .exclude(id=rel.id)
                .exclude(host_product_id=rel.accessory_product_id)
                .first()
            )
            pick = sibling.host_product if sibling else None
        if pick is None and rel.host_model_key:
            # 退路二:沒掛主檔的舊商品。它們算出來的機型 key 跟這列一樣
            # 就是同一款,只是從來沒被收進主檔(regex 那條路)。
            candidates = (
                Product.objects.filter(tenant_id=rel.tenant_id)
                .exclude(id=rel.accessory_product_id)
                .only("id", "name", "series_id", "generation", "model_suffix")
            )
            for cand in candidates.iterator(chunk_size=500):
                nm = _model_name_for_reverse(cand, series_names.get(cand.series_id))
                if nm and nm.strip().lower() == rel.host_model_key:
                    pick = cand
                    break
        if pick is None:
            stuck.append(rel)
            continue
        rel.host_product_id = pick.id
        rel.save(update_fields=["host_product"])

    # 同一個 transaction 內剛寫過這張表,PostgreSQL 會留著延後的外鍵 trigger,
    # 接下來的 ALTER TABLE 會被擋成 "pending trigger events"。先讓它們立刻檢查完。
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")

    if stuck:
        ids = ", ".join(str(r.id) for r in stuck[:10])
        raise RuntimeError(
            "無法退版:這些相容關係的代表 SKU 已被刪光,找不到同機型的替代品 "
            f"(ProductRelation id: {ids})。"
            "請先為這些機型補一支商品,或自行決定要不要刪掉這些關聯。"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_condition_tracks_unit_condition'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrelation',
            name='host_product',
            field=models.ForeignKey(blank=True, help_text='該機型的代表 SKU(任一),只用於 UI 顯示範例。刪掉這支 SKU 不該讓整組相容關係跟著消失,所以是 SET_NULL 不是 CASCADE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_relations', to='catalog.product', verbose_name='主機代表 SKU'),
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.SlugField(max_length=40, verbose_name='代碼')),
                ('name', models.CharField(max_length=128, verbose_name='機型名稱')),
                ('match_key', models.CharField(db_index=True, help_text='lowercase 機型名稱;舊資料對應與新商品自動歸位用,不是身分', max_length=128, verbose_name='比對鍵')),
                ('generation', models.PositiveIntegerField(blank=True, null=True, verbose_name='世代')),
                ('model_suffix', models.CharField(blank=True, default='', max_length=30, verbose_name='型號後綴')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone_models', to='catalog.brand', verbose_name='品牌')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone_models', to='catalog.phoneseries', verbose_name='系列')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '機型',
                'verbose_name_plural': '機型',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='phone_model',
            field=models.ForeignKey(blank=True, help_text='穩定的機型身分。舊資料為 NULL 時退回 phone_model_key 那個算出來的字串,行為不變', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.phonemodel', verbose_name='機型'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='host_model',
            field=models.ForeignKey(blank=True, help_text='穩定的機型身分;舊資料為 NULL 時以 host_model_key 為準', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessory_relations', to='catalog.phonemodel', verbose_name='主機機型'),
        ),
        migrations.AddIndex(
            model_name='phonemodel',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_pho_tenant__78c912_idx'),
        ),
        migrations.AddConstraint(
            model_name='phonemodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_phone_model_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='phonemodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'match_key'), name='uniq_phone_model_tenant_match_key'),
        ),
        # 這一支只有「反向」有事做:退版時 host_product 會被改回 NOT NULL,
        # 但代表 SKU 被刪過的關聯此時是 NULL,直接退會噴
        # "column host_product_id contains null values"。
        # 反向操作是倒著跑的,所以放在最後 = 退版時最先執行。
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=_refill_host_product
        ),
    ]
