# Generated by Django 5.1.4 on 2026-09-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_backfill_phone_model'),
        ('parties', '0015_supplier_is_repair_vendor'),
        ('tenants', '0015_next_style_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='無品牌配件的穩定款式編號(例:042)。店員不用自己想名字,容易撞名的款式用「透明磁吸防摔殼 042」這樣區分', max_length=20, verbose_name='款式碼'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('platform', models.CharField(blank=True, default='', help_text='例:淘寶 / 蝦皮 / 官網 / 電話下單', max_length=40, verbose_name='平台')),
                ('page_id', models.CharField(blank=True, db_index=True, default='', help_text='平台上的商品編號;同一頁可能有多個變體', max_length=120, verbose_name='商品頁 ID')),
                ('variant', models.CharField(blank=True, default='', help_text='顏色 / 機型 / 材質 / 包裝,例:透明-iPhone15Pro-10入', max_length=200, verbose_name='選到的變體')),
                ('vendor_sku', models.CharField(blank=True, db_index=True, default='', help_text='**變體層**的料號(對到一個實際可下單的規格),不是父商品料號', max_length=80, verbose_name='廠商料號')),
                ('vendor_sku_key', models.CharField(blank=True, db_index=True, default='', help_text='vendor_sku 正規化後的字,系統自動算。查重與唯一鍵都用它 —— 用原字的話 ABC-01 / abc-01 / ＡＢＣ－０１ 會被當成三個不同料號,跟別名表(它用正規化鍵)對不起來', max_length=200, verbose_name='料號比對鍵')),
                ('source_name_key', models.CharField(blank=True, db_index=True, default='', help_text='source_name 正規化後的字,系統自動算;沒有料號時靠它去重', max_length=200, verbose_name='來源品名比對鍵')),
                ('source_name', models.CharField(blank=True, default='', help_text='廠商自己的叫法,原樣保留;不要拿來當店內品名', max_length=300, verbose_name='來源品名')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='連結')),
                ('pack_qty', models.PositiveIntegerField(default=1, help_text='來源一件等於店內幾個計量單位(一盒 10 片就填 10)', verbose_name='一單位幾入')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認時間')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_supplier_products', to=settings.AUTH_USER_MODEL, verbose_name='確認人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='catalog.product', verbose_name='對應商品')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='parties.supplier', verbose_name='供應商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '供應商商品對照',
                'verbose_name_plural': '供應商商品對照',
                'ordering': ['supplier', 'product'],
                'indexes': [models.Index(fields=['tenant', 'product'], name='catalog_sup_tenant__e617ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('vendor_sku_key', ''), _negated=True)), fields=('tenant', 'supplier', 'vendor_sku_key'), name='uniq_supplier_product_vendor_sku'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('vendor_sku_key', ''), ('page_id', ''), models.Q(('source_name_key', ''), _negated=True)), fields=('tenant', 'supplier', 'product', 'source_name_key'), name='uniq_supplier_product_auto_source'), models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('page_id', ''), _negated=True), models.Q(('variant', ''), _negated=True)), fields=('tenant', 'supplier', 'platform', 'page_id', 'variant'), name='uniq_supplier_product_page_variant')],
            },
        ),
    ]
