# Generated by Django 5.1.4 on 2026-09-26 17:45

from django.db import migrations, models

# 預設 True(要掛機型),只有這些類別關掉:
# - 主機本身(手機 / 平板 / 手錶):它們是被掛的那一方,不是配件
# - 整個類別都跟機型無關:吊飾、支架、家電(風扇 / 刮鬍刀 / 電視盒)、包膜服務、虛擬商品
#
# **刻意不關「充電/線材」與「耳機/音訊」**:整體看起來是通用品,但實測裡面確實有
# 機型專屬的(`IP5/副廠/2M`、`SAM/S10/S10+` 耳機、`SAM/NOTE4` 充電線)。
# 整個類別關掉會把這些漏掉;留著 True,交給逐件品名的通用配件判斷處理——
# 實測那兩類 165 / 68 筆裡,逐件判斷已經正確認出 133 / 46 筆是通用品。
#
# 名單照既有類別名稱寫。租戶自訂類別名不在名單裡的一律保持 True(要掛),
# 寧可多問一次也不要靜默漏掉——之後在類別設定頁自己關即可。
NO_HOST_MODEL = (
    "手機", "平板", "手錶",
    "掛繩/吊飾", "支架/車架", "家電", "包膜", "虛擬",
)


def turn_off_for_model_independent(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Category.objects.filter(name__in=NO_HOST_MODEL).update(needs_host_model=False)


def turn_all_back_on(apps, schema_editor):
    """反向遷移:欄位本身會被拿掉,這裡只是讓 migration 可逆不報錯。"""
    Category = apps.get_model("catalog", "Category")
    Category.objects.all().update(needs_host_model=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_supplier_product_and_style_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='needs_host_model',
            field=models.BooleanField(default=True, help_text='這個類別的商品要不要掛「相容哪些機型」(ProductRelation)。主機本身(手機 / 平板 / 手錶)不用掛;線材、吊飾、家電這種跟機型無關的也不用。關掉之後這類商品不會出現在「待補相容機型」的待辦裡', verbose_name='需要掛相容機型'),
        ),
        migrations.RunPython(turn_off_for_model_independent, turn_all_back_on),
    ]
