# Generated by Django 5.1.4 on 2026-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_category_needs_host_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='staff_cost_mode',
            field=models.CharField(blank=True, choices=[('', '照全公司'), ('fixed', '固定金額'), ('plus', '加固定額'), ('percent', '加百分比')], default='', help_text='空的 = 照全公司的設定', max_length=10, verbose_name='業務員成本算法'),
        ),
        migrations.AddField(
            model_name='product',
            name='staff_cost_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='固定金額 = 每一件幾元;加固定額 = 成本加幾元;加百分比 = 成本加幾 %', max_digits=14, verbose_name='業務員成本數值'),
        ),
    ]
