# Generated by Django 5.1.4 on 2026-10-04 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0027_category_needs_host_model'),
        ('inventory', '0010_productserialidentifier'),
        ('tenants', '0017_userprofile_account_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('business_date', models.DateField(verbose_name='營業日')),
                ('started_at', models.DateTimeField(verbose_name='開始')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='結束')),
                ('ok', models.BooleanField(default=False, verbose_name='全部一致')),
                ('problem_count', models.PositiveIntegerField(default=0, verbose_name='不一致項目數')),
                ('results', models.JSONField(default=list, verbose_name='結果')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '每日對帳',
                'verbose_name_plural': '每日對帳',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'business_date'], name='ledger_check_day')],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('business_date', models.DateField(verbose_name='營業日')),
                ('state', models.CharField(choices=[('in_stock', '在庫'), ('returned', '退回待處理'), ('rma', '維修中'), ('in_transit', '調撥中')], max_length=20, verbose_name='狀態')),
                ('qty', models.PositiveIntegerField(verbose_name='數量')),
                ('cost_value', models.DecimalField(decimal_places=2, help_text='序號 = 各台進貨成本加總;配件 = 數量 × 該門市加權平均;調撥中配件 = 派發時成本', max_digits=16, verbose_name='成本金額(未稅)')),
                ('taken_at', models.DateTimeField(verbose_name='記錄時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(blank=True, help_text='調撥中記在目的門市;找不到調撥單的留空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse', verbose_name='門市')),
            ],
            options={
                'verbose_name': '每日庫存快照',
                'verbose_name_plural': '每日庫存快照',
                'ordering': ['-business_date', 'warehouse_id', 'product_id'],
                'indexes': [models.Index(fields=['tenant', 'business_date'], name='stock_snapshot_day')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'business_date', 'warehouse', 'product', 'state'), name='uniq_stock_snapshot_day', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshotDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('business_date', models.DateField(verbose_name='營業日')),
                ('taken_at', models.DateTimeField(verbose_name='記錄時間')),
                ('row_count', models.PositiveIntegerField(verbose_name='列數')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '每日庫存快照紀錄',
                'verbose_name_plural': '每日庫存快照紀錄',
                'ordering': ['-business_date'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'business_date'), name='uniq_stock_snapshot_day_marker')],
            },
        ),
    ]
