# Generated by Django 5.1.4 on 2026-10-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyproductmap',
            name='product_name_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='看到這個品名的擷取時間'),
        ),
    ]
