# Generated by Django 5.1.4 on 2026-05-17 12:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('inventory', '0002_alter_productserial_options_and_more'),
        ('parties', '0001_initial'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('no', models.CharField(blank=True, editable=False, help_text='系統自動產生:PO-{6位流水}', max_length=30, verbose_name='單號')),
                ('doc_date', models.DateField(default=datetime.date.today, verbose_name='單據日期')),
                ('extra_cost_total', models.DecimalField(decimal_places=2, default=0, help_text='運費 / 關稅 / 保險等,過帳時按金額比例攤到每筆明細', max_digits=14, verbose_name='附加費用合計')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('posted', '已過帳'), ('void', '作廢')], default='draft', max_length=10, verbose_name='狀態')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='過帳時間')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='貨款小計')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='含費用總額')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作業者')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='parties.supplier', verbose_name='供應商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse', verbose_name='入庫倉')),
            ],
            options={
                'verbose_name': '進貨單',
                'verbose_name_plural': '進貨單',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行號')),
                ('qty', models.PositiveIntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='單價')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='數量 × 單價,系統計算', max_digits=14, verbose_name='金額')),
                ('serial_numbers', models.JSONField(blank=True, default=list, help_text='逐台 IMEI / SN 字串清單;長度需等於數量', verbose_name='序號列表')),
                ('allocated_extra_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='分攤附加費用')),
                ('unit_landed_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='攤提後單台成本')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder', verbose_name='進貨單')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '進貨明細',
                'verbose_name_plural': '進貨明細',
                'ordering': ['po', 'line_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'no'), name='uniq_po_tenant_no'),
        ),
    ]
