# Generated by Django 5.1.4 on 2026-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_void',
            field=models.BooleanField(default=False, verbose_name='作廢'),
        ),
    ]
