# Generated by Django 5.1.4 on 2026-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_remove_purchaseorder_posted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='extra_cost_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='allocated_extra_cost',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='稅額'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_method',
            field=models.CharField(choices=[('taxable_included', '應稅內含'), ('taxable_excluded', '應稅外加'), ('tax_free', '免稅'), ('zero_tax', '零稅')], default='taxable_included', max_length=20, verbose_name='課稅別'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='未稅小計'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='含稅總額'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_landed_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='含稅單時 = unit_price / 1.05;其他 = unit_price', max_digits=14, verbose_name='單台落地成本(未稅)'),
        ),
    ]
