# Generated by Django 5.1.4 on 2026-05-18 12:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_billed_qty(apps, schema_editor):
    """既有資料無贈品,billed_qty 直接帶 qty。"""
    Item = apps.get_model("purchasing", "PurchaseOrderItem")
    Item.objects.filter(billed_qty=0).update(billed_qty=models.F("qty"))


def seed_default_category(apps, schema_editor):
    """每個 tenant 預設一筆「一般進貨」。"""
    Tenant = apps.get_model("tenants", "Tenant")
    Cat = apps.get_model("purchasing", "PurchaseOrderCategory")
    for t in Tenant.objects.all():
        Cat.objects.get_or_create(
            tenant=t,
            code="A01",
            defaults={"name": "一般進貨", "sort_order": 1, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_remove_purchaseorder_extra_cost_total_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='發票日期'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_form',
            field=models.CharField(choices=[('none', '免用統一發票'), ('duplicate', '二聯式'), ('triplicate', '三聯式'), ('electronic', '電子發票'), ('cash_register', '收銀機發票')], default='none', max_length=20, verbose_name='發票聯數'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='發票號碼'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='billed_qty',
            field=models.PositiveIntegerField(default=0, help_text='實際計價的數量(贈品/試用品不計價);未設定 → 等於進貨數量', verbose_name='計價數量'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='qty',
            field=models.PositiveIntegerField(help_text='實際入庫數量(含贈品)', verbose_name='進貨數量'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=10, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '進貨單別',
                'verbose_name_plural': '進貨單別',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.purchaseordercategory', verbose_name='進貨單別'),
        ),
        migrations.AddConstraint(
            model_name='purchaseordercategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_po_category_tenant_code'),
        ),
        migrations.RunPython(backfill_billed_qty, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_default_category, reverse_code=migrations.RunPython.noop),
    ]
