# Generated by Django 5.1.4 on 2026-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseorder_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_form',
            field=models.CharField(blank=True, default='', help_text='存 InvoiceType.code', max_length=20, verbose_name='發票類型'),
        ),
    ]
