# Generated by Django 5.1.4 on 2026-05-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_purchaseorder_invoice_form'),
        ('tenants', '0008_tenant_next_expense_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='cash=從店頭備用金扣;transfer/non_cash=不動店頭現金', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tenants.paymentmethod', verbose_name='付款方式'),
        ),
    ]
