# Generated by Django 5.1.4 on 2026-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_purchaseorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_method',
            field=models.CharField(choices=[('taxable_included', '應稅內含'), ('taxable_excluded', '應稅外加'), ('untaxed', '未稅'), ('tax_free', '免稅'), ('zero_tax', '零稅')], default='taxable_included', max_length=20, verbose_name='課稅別'),
        ),
    ]
