# Generated by Django 5.1.4 on 2026-10-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_alter_purchaseorder_tax_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='billed_qty',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='實際計價的數量(贈品/試用品不計價);沒填 → 等於進貨數量;填 0 = 整行不計價', null=True, verbose_name='計價數量'),
        ),
    ]
