# Generated by Django 5.1.4 on 2026-10-06 08:02

import apps.photos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0027_category_needs_host_model'),
        ('tenants', '0017_userprofile_account_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='作業識別')),
                ('label', models.CharField(blank=True, max_length=160, verbose_name='品名')),
                ('spec', models.CharField(blank=True, max_length=160, verbose_name='規格')),
                ('state', models.CharField(choices=[('open', '進行中'), ('committed', '已隨商品儲存'), ('cancelled', '已取消')], default='open', max_length=12, verbose_name='狀態')),
                ('frozen', models.BooleanField(default=False, verbose_name='電腦正在儲存')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('pair_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='配對憑證雜湊')),
                ('pair_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='QR Code 有效到')),
                ('device_hash', models.CharField(blank=True, max_length=64, verbose_name='手機識別雜湊')),
                ('paired_at', models.DateTimeField(blank=True, null=True, verbose_name='手機連上時間')),
                ('device_active_at', models.DateTimeField(blank=True, null=True, verbose_name='手機最後動作時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '商品照片作業',
                'verbose_name_plural': '商品照片作業',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('uid', models.CharField(max_length=64, verbose_name='上傳識別')),
                ('source', models.CharField(choices=[('desktop', '電腦'), ('phone', '手機')], default='desktop', max_length=8, verbose_name='來源')),
                ('status', models.CharField(choices=[('uploading', '上傳中'), ('ready', '可用'), ('failed', '失敗'), ('cancelled', '已取消')], default='uploading', max_length=10, verbose_name='狀態')),
                ('image', models.FileField(blank=True, upload_to=apps.photos.models._photo_path, verbose_name='大圖')),
                ('thumb', models.FileField(blank=True, upload_to=apps.photos.models._photo_path, verbose_name='縮圖')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='寬')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='高')),
                ('error', models.CharField(blank=True, max_length=200, verbose_name='失敗原因')),
                ('consumed', models.BooleanField(default=False, verbose_name='已掛到商品')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='photos.photodraft', verbose_name='作業')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '暫存照片',
                'verbose_name_plural': '暫存照片',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'uid'), name='uniq_photo_upload_uid')],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('image', models.FileField(upload_to=apps.photos.models._photo_path, verbose_name='大圖')),
                ('thumb', models.FileField(upload_to=apps.photos.models._photo_path, verbose_name='縮圖')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='寬')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='高')),
                ('caption', models.CharField(blank=True, max_length=40, verbose_name='說明')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主圖')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '商品照片',
                'verbose_name_plural': '商品照片',
                'ordering': ['-is_primary', 'sort', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='uniq_product_primary_photo')],
            },
        ),
    ]
