# Generated by Django 5.1.4 on 2026-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['id'], 'verbose_name': '租戶', 'verbose_name_plural': '租戶'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.SlugField(max_length=40, unique=True, verbose_name='代碼'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=120, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
