# Generated by Django 5.1.4 on 2026-05-18 15:18

import django.db.models.deletion
from django.db import migrations, models


SEED = [
    ("e_invoice", "電子發票", 10, True),
    ("ev_dup", "電子二聯式", 20, False),
    ("ev_tri", "電子三聯式", 30, False),
    ("hand_dup", "手開二聯", 40, False),
    ("hand_tri", "手開三聯", 50, False),
    ("none", "免用統一發票", 90, False),
]


def seed_invoice_types(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    IT = apps.get_model("tenants", "InvoiceType")
    for t in Tenant.objects.all():
        for code, name, sort_order, is_default in SEED:
            IT.objects.get_or_create(
                tenant=t,
                code=code,
                defaults={
                    "name": name,
                    "sort_order": sort_order,
                    "is_active": True,
                    "is_default": is_default,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=20, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='顯示名稱')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '發票類型',
                'verbose_name_plural': '發票類型',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_invoice_type_tenant_code')],
            },
        ),
        migrations.RunPython(seed_invoice_types, reverse_code=migrations.RunPython.noop),
    ]
