# Generated by Django 5.1.4 on 2026-05-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_invoicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('period_label', models.CharField(blank=True, help_text='例:115年5-6月', max_length=30, verbose_name='期別')),
                ('prefix', models.CharField(max_length=4, verbose_name='字軌')),
                ('range_start', models.PositiveIntegerField(verbose_name='起號')),
                ('range_end', models.PositiveIntegerField(verbose_name='迄號')),
                ('next_number', models.PositiveIntegerField(help_text='開檔時 = 起號;每開一張遞增 1', verbose_name='下一張號碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('invoice_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='tenants.invoicetype', verbose_name='發票類型')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '發票字軌',
                'verbose_name_plural': '發票字軌',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'prefix', 'range_start'), name='uniq_invoice_track_prefix_start'), models.CheckConstraint(condition=models.Q(('range_end__gte', models.F('range_start'))), name='invoice_track_end_gte_start')],
            },
        ),
    ]
