# Generated by Django 5.1.4 on 2026-05-18 16:34

import django.db.models.deletion
from django.db import migrations, models


SEED = [
    # code, name, kind, sort_order, is_default
    ("cash", "現金", "cash", 10, True),
    ("card", "信用卡", "non_cash", 20, False),
    ("transfer", "匯款", "transfer", 30, False),
]


def seed_payment_methods(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    PM = apps.get_model("tenants", "PaymentMethod")
    for t in Tenant.objects.all():
        for code, name, kind, sort_order, is_default in SEED:
            PM.objects.get_or_create(
                tenant=t,
                code=code,
                defaults={
                    "name": name,
                    "kind": kind,
                    "sort_order": sort_order,
                    "is_active": True,
                    "is_default": is_default,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_invoicetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=20, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='顯示名稱')),
                ('kind', models.CharField(choices=[('cash', '現金'), ('transfer', '匯款'), ('non_cash', '非現金')], max_length=20, verbose_name='分類')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '付款方式',
                'verbose_name_plural': '付款方式',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_payment_method_tenant_code')],
            },
        ),
        migrations.RunPython(seed_payment_methods, reverse_code=migrations.RunPython.noop),
    ]
