# Generated by Django 5.1.4 on 2026-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_supplier_seq',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='下一供應商流水'),
        ),
    ]
