# Generated by Django 5.1.4 on 2026-05-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_next_supplier_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_customer_seq',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='下一客戶流水'),
        ),
    ]
