# Generated by Django 5.1.4 on 2026-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_next_customer_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_expense_seq',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='下一雜支單流水'),
        ),
    ]
