# Generated by Django 5.1.4 on 2026-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_next_expense_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_cash_adj_seq',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='下一現金調整流水'),
        ),
    ]
