# Generated by Django 5.1.4 on 2026-05-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_next_member_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_phone_bill_seq',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='下一代收話費流水'),
        ),
    ]
