# Generated by Django 5.1.4 on 2026-05-26 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_warehouse_address_warehouse_phone'),
        ('tenants', '0011_tenant_next_phone_bill_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('role', models.CharField(choices=[('platform_admin', '平台管理員'), ('tenant_admin', '經銷商管理員'), ('tenant_user', '店員')], default='tenant_user', max_length=20, verbose_name='角色')),
                ('is_warehouse_locked', models.BooleanField(default=True, help_text='True 時只能操作 default_warehouse;管理員角色預設 False', verbose_name='鎖定門市')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_profiles', to='inventory.warehouse', verbose_name='預設門市')),
                ('tenant', models.ForeignKey(blank=True, help_text='platform_admin 留空,其他必填', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='tenants.tenant', verbose_name='所屬經銷商')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者設定',
                'verbose_name_plural': '使用者設定',
            },
        ),
    ]
