# Generated by Django 5.1.4 on 2026-09-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_style_seq',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='下一款式碼流水'),
        ),
    ]
