# Generated by Django 5.1.4 on 2026-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_userprofile_account_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contract_remind_months',
            field=models.PositiveSmallIntegerField(default=3, help_text='門號合約到期前幾個月開始出現在「合約到期」的待聯絡名單', verbose_name='門號合約到期前幾個月提醒'),
        ),
    ]
