# Generated by Django 5.1.4 on 2026-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_contract_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='staff_cost_mode',
            field=models.CharField(blank=True, choices=[('', '尚未設定'), ('plus', '加固定額'), ('percent', '加百分比')], default='', help_text='空的 = 尚未設定(業務員成本 = 實際成本)', max_length=10, verbose_name='業務員成本算法'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='staff_cost_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='加固定額 = 每一件加幾元;加百分比 = 加幾 %', max_digits=14, verbose_name='業務員成本加多少'),
        ),
    ]
