# Generated by Django 5.1.4 on 2026-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_staff_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='denied_abilities',
            field=models.JSONField(blank=True, default=list, help_text='項目代碼的清單;空的 = 全部可以做(管理員永遠全開)', verbose_name='關掉的權限'),
        ),
    ]
