# Generated by Django 5.1.4 on 2026-05-24 10:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_stockmovement_product_stockmovement_qty_and_more'),
        ('tenants', '0008_tenant_next_expense_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('no', models.CharField(blank=True, editable=False, help_text='系統自動產生:EX-{5位流水}', max_length=20, verbose_name='單號')),
                ('doc_date', models.DateField(default=datetime.date.today, verbose_name='單據日期')),
                ('category', models.CharField(choices=[('rent', '房租'), ('utility', '水電網路'), ('meal', '餐飲'), ('supplies', '雜物 / 文具'), ('other', '其他')], default='other', max_length=20, verbose_name='類別')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='支出金額(整數元)', max_digits=14, verbose_name='金額')),
                ('payee', models.CharField(blank=True, help_text='例:房東 / 7-11 / 中華電信', max_length=120, verbose_name='收款對象')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_void', models.BooleanField(default=False, verbose_name='作廢')),
                ('payment_method', models.ForeignKey(help_text='預設現金;若是匯款則不影響店頭備用金', on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='tenants.paymentmethod', verbose_name='付款方式')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(help_text='記在哪家門市的帳上', on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='inventory.warehouse', verbose_name='門市')),
            ],
            options={
                'verbose_name': '雜支單',
                'verbose_name_plural': '雜支單',
                'ordering': ['-doc_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'no'), name='uniq_petty_expense_no')],
            },
        ),
    ]
