# Generated by Django 5.1.4 on 2026-05-24 11:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('inventory', '0006_stockmovement_product_stockmovement_qty_and_more'),
        ('tenants', '0009_tenant_next_cash_adj_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('no', models.CharField(blank=True, editable=False, help_text='系統自動產生:CA-{5位流水}', max_length=20, verbose_name='單號')),
                ('doc_date', models.DateField(default=datetime.date.today, verbose_name='單據日期')),
                ('direction', models.CharField(choices=[('in', '存入(老闆補錢)'), ('out', '提取(領出 / 存銀行)')], default='in', max_length=10, verbose_name='方向')),
                ('reason', models.CharField(choices=[('refill', '補充備用金'), ('deposit', '領現存銀行'), ('owner_take', '老闆領用'), ('adjustment', '盤點校正'), ('other', '其他')], default='refill', max_length=20, verbose_name='事由')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='正數,方向由 direction 決定 + / -', max_digits=14, verbose_name='金額')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_void', models.BooleanField(default=False, verbose_name='作廢')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_adjustments', to='inventory.warehouse', verbose_name='門市')),
            ],
            options={
                'verbose_name': '現金調整',
                'verbose_name_plural': '現金調整',
                'ordering': ['-doc_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'no'), name='uniq_cash_adjustment_no')],
            },
        ),
    ]
