# Generated by Django 5.1.4 on 2026-05-26 01:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_cashadjustment_handled_by'),
        ('inventory', '0007_alter_productserial_acquired_from_member'),
        ('parties', '0013_remove_customer_is_member'),
        ('tenants', '0011_tenant_next_phone_bill_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBillCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('no', models.CharField(blank=True, editable=False, help_text='系統自動產生:PB-{5位流水}', max_length=20, verbose_name='單號')),
                ('doc_date', models.DateField(default=datetime.date.today, verbose_name='單據日期')),
                ('phone_no', models.CharField(help_text='繳費對應的完整電話號碼', max_length=20, verbose_name='電話號碼')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='繳費金額(整數元)', max_digits=14, verbose_name='金額')),
                ('id_no', models.CharField(help_text='收據顯示時會做隱碼處理', max_length=20, verbose_name='身分證字號')),
                ('is_void', models.BooleanField(default=False, verbose_name='作廢')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_bills', to='parties.carrier', verbose_name='電信業者')),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_bills_handled', to='parties.salesperson', verbose_name='經手人')),
                ('member', models.ForeignKey(blank=True, help_text='phone_no 對到會員主檔時自動掛上', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_bills', to='parties.member', verbose_name='會員')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(help_text='收費歸到哪家門市的現金櫃', on_delete=django.db.models.deletion.PROTECT, related_name='phone_bills', to='inventory.warehouse', verbose_name='門市')),
            ],
            options={
                'verbose_name': '代收話費',
                'verbose_name_plural': '代收話費',
                'ordering': ['-doc_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'no'), name='uniq_phone_bill_no')],
            },
        ),
    ]
