# Generated by Django 5.1.4 on 2026-10-02 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0016_backup_uuid_and_doc_number_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('kind', models.CharField(choices=[('manual', '手動備份'), ('safety', '還原前安全備份')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('queued', '排隊中'), ('running', '產生中'), ('verified', '已驗證,可下載'), ('failed', '失敗'), ('expired', '已過期')], db_index=True, default='queued', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='已嘗試次數')),
                ('lease_until', models.DateTimeField(blank=True, null=True, verbose_name='租約到期')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('backup_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='備份編號')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='檔名(相對於備份目錄)')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='檔案大小')),
                ('file_sha256', models.CharField(blank=True, max_length=64, verbose_name='檔案雜湊')),
                ('snapshot_at', models.DateTimeField(blank=True, null=True, verbose_name='資料時間點')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='內容摘要')),
                ('error', models.TextField(blank=True, verbose_name='失敗原因')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='下載期限')),
                ('download_started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始下載')),
                ('local_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='本機檔案驗證')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='發起者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='tenants.tenant', verbose_name='公司')),
            ],
            options={
                'verbose_name': '備份工作',
                'verbose_name_plural': '備份工作',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BackupKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('wrapped', models.TextField(verbose_name='包過的憑證')),
                ('fingerprint', models.CharField(max_length=16, verbose_name='核對碼')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='確認已保管')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='產生者')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_key', to='tenants.tenant', verbose_name='公司')),
            ],
            options={
                'verbose_name': '復原憑證',
                'verbose_name_plural': '復原憑證',
            },
        ),
        migrations.CreateModel(
            name='DownloadTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backup.backupjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '下載票券',
                'verbose_name_plural': '下載票券',
            },
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('mode', models.CharField(choices=[('rollback', '既有公司回溯'), ('new_env', '新環境復原')], default='rollback', max_length=10)),
                ('status', models.CharField(choices=[('prechecked', '已預檢,待確認'), ('rejected', '預檢未通過'), ('queued', '排隊中'), ('running', '還原中'), ('done', '已完成'), ('failed', '失敗,資料未變動'), ('needs_attention', '中斷,需人工確認'), ('cancelled', '已取消')], db_index=True, default='prechecked', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('staged_file', models.CharField(blank=True, max_length=200, verbose_name='暫存檔(相對於備份目錄)')),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='預檢報告')),
                ('target_fingerprint', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='還原結果')),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='預檢有效期限')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('safety_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backup.backupjob', verbose_name='還原前安全備份')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_jobs', to='tenants.tenant', verbose_name='目標公司')),
            ],
            options={
                'verbose_name': '還原工作',
                'verbose_name_plural': '還原工作',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BackupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='時間')),
                ('tenant_uuid', models.CharField(blank=True, max_length=36, verbose_name='公司識別碼')),
                ('actor_name', models.CharField(blank=True, max_length=150, verbose_name='操作者帳號')),
                ('action', models.CharField(max_length=40, verbose_name='動作')),
                ('ok', models.BooleanField(default=True, verbose_name='成功')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='細節')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant', verbose_name='公司')),
                ('backup_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backup.backupjob')),
                ('restore_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backup.restorejob')),
            ],
            options={
                'verbose_name': '備份操作紀錄',
                'verbose_name_plural': '備份操作紀錄',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TenantMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('active', models.BooleanField(default=False, verbose_name='維護中')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='原因')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('restore_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backup.restorejob')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='tenants.tenant', verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司維護鎖',
                'verbose_name_plural': '公司維護鎖',
            },
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['tenant', 'status'], name='backup_back_tenant__7e15a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='backupjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_backup_job_idempotency'),
        ),
        migrations.AddIndex(
            model_name='restorejob',
            index=models.Index(fields=['tenant', 'status'], name='backup_rest_tenant__0ec1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='backupauditlog',
            index=models.Index(fields=['tenant', '-id'], name='backup_back_tenant__e04a2c_idx'),
        ),
    ]
