# Generated by Django 5.1.4 on 2026-05-17 13:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('inventory', '0003_productserial_purchase_order_item'),
        ('parties', '0001_initial'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('no', models.CharField(blank=True, editable=False, help_text='系統自動產生:SO-{6位流水}', max_length=30, verbose_name='單號')),
                ('doc_date', models.DateField(default=datetime.date.today, verbose_name='單據日期')),
                ('sales_type', models.CharField(choices=[('sale', '一般銷售'), ('online', '線上訂單'), ('promo', '促銷')], default='sale', max_length=10, verbose_name='銷貨類別')),
                ('tax_method', models.CharField(choices=[('taxable_included', '應稅內含'), ('taxable_excluded', '應稅外加'), ('tax_free', '免稅'), ('zero_tax', '零稅')], default='taxable_included', max_length=20, verbose_name='課稅別')),
                ('invoice_no', models.CharField(blank=True, help_text='Phase 3 接電子發票後自動產生', max_length=20, verbose_name='發票號碼')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('posted', '已過帳'), ('void', '作廢')], default='draft', max_length=10, verbose_name='狀態')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='過帳時間')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='未稅小計')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='稅額')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='含稅總額')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作業者')),
                ('customer', models.ForeignKey(blank=True, help_text='散客可不填', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='parties.customer', verbose_name='客戶')),
                ('sales_person', models.ForeignKey(blank=True, help_text='業績歸屬', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='業務員')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.warehouse', verbose_name='出貨倉')),
            ],
            options={
                'verbose_name': '銷貨單',
                'verbose_name_plural': '銷貨單',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行號')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='單價')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='數量 × 單價,系統計算', max_digits=14, verbose_name='金額')),
                ('cost_at_post', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='過帳時鎖定為 Product.weighted_avg_cost,供毛利報表用', max_digits=14, verbose_name='過帳當下單台成本')),
                ('sim_card_no', models.CharField(blank=True, max_length=25, verbose_name='SIM 卡號 (ICCID)')),
                ('msisdn', models.CharField(blank=True, max_length=20, verbose_name='門號')),
                ('telecom_plan_code', models.CharField(blank=True, max_length=20, verbose_name='促銷方案代碼')),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Phase 2 由方案自動帶入', max_digits=14, verbose_name='業務員佣金')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='上線日')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='catalog.product', verbose_name='商品')),
                ('serial', models.ForeignKey(blank=True, help_text='requires_serial 商品必填;過帳時驗證', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='inventory.productserial', verbose_name='出貨序號')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='銷貨單')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '銷貨明細',
                'verbose_name_plural': '銷貨明細',
                'ordering': ['so', 'line_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'no'), name='uniq_so_tenant_no'),
        ),
    ]
