# Generated by Django 5.1.4 on 2026-05-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_salesperson'),
        ('sales', '0002_remove_salesorder_posted_at_remove_salesorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='buyer_tax_id',
            field=models.CharField(blank=True, help_text='應稅時填寫,免稅 / 零稅留空', max_length=20, verbose_name='買方統一編號'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sales_person',
            field=models.ForeignKey(blank=True, help_text='業績歸屬', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='parties.salesperson', verbose_name='業務員'),
        ),
    ]
