# Generated by Django 5.1.4 on 2026-05-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_carrier_telecomplan_carrier_uniq_carrier_tenant_code_and_more'),
        ('sales', '0003_salesorder_buyer_tax_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='telecom_plan_code',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='telecom_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='parties.telecomplan', verbose_name='電信方案'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='選方案後自動帶入,可手動覆寫', max_digits=14, verbose_name='業務員佣金'),
        ),
    ]
