# Generated by Django 5.1.4 on 2026-05-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_simcard'),
        ('sales', '0004_remove_salesorderitem_telecom_plan_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='sim_card_no',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sim_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='parties.simcard', verbose_name='SIM 卡'),
        ),
    ]
