# Generated by Django 5.1.4 on 2026-05-18 14:03

import django.db.models.deletion
from django.db import migrations, models


def migrate_serial_to_join(apps, schema_editor):
    """把 SalesOrderItem.serial 既有資料搬到 SalesOrderItemSerial。"""
    Item = apps.get_model("sales", "SalesOrderItem")
    Join = apps.get_model("sales", "SalesOrderItemSerial")
    for it in Item.objects.exclude(serial__isnull=True):
        Join.objects.get_or_create(
            tenant=it.tenant,
            item=it,
            serial_id=it.serial_id,
            defaults={"line_pos": 0},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productserial_purchase_order_item'),
        ('sales', '0005_remove_salesorderitem_sim_card_no_and_more'),
        ('tenants', '0002_alter_tenant_options_alter_tenant_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='使用者填入的實收金額;未填則 fallback 為 數量 × 單價', max_digits=14, verbose_name='金額'),
        ),
        # 1. 先建中介表
        migrations.CreateModel(
            name='SalesOrderItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('line_pos', models.PositiveIntegerField(default=0, verbose_name='位序')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='sales.salesorderitem', verbose_name='銷貨明細')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_item_serials', to='inventory.productserial', verbose_name='序號')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '銷貨明細序號',
                'verbose_name_plural': '銷貨明細序號',
                'ordering': ['item', 'line_pos', 'id'],
            },
        ),
        # 2. 搬資料
        migrations.RunPython(migrate_serial_to_join, reverse_code=migrations.RunPython.noop),
        # 3. 才能安全砍欄
        migrations.RemoveField(
            model_name='salesorderitem',
            name='serial',
        ),
    ]
