# Generated by Django 5.1.4 on 2026-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_salesorderitem_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='發票日期'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_form',
            field=models.CharField(blank=True, default='', help_text='存 InvoiceType.code;允許空字串=未指定', max_length=20, verbose_name='發票類型'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='發票號碼'),
        ),
    ]
