# Generated by Django 5.1.4 on 2026-05-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesorder_invoice_date_salesorder_invoice_form_and_more'),
        ('tenants', '0004_invoicetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('method', models.CharField(choices=[('cash', '現金'), ('card', '刷卡')], max_length=20, verbose_name='付款方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金額')),
                ('note', models.CharField(blank=True, help_text='例:卡號末 4 碼 / 收據編號', max_length=100, verbose_name='備註')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行號')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesorder', verbose_name='銷貨單')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '銷貨付款',
                'verbose_name_plural': '銷貨付款',
                'ordering': ['so', 'line_no', 'id'],
            },
        ),
    ]
