# Generated by Django 5.1.4 on 2026-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesorderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderpayment',
            name='method',
            field=models.CharField(help_text='對應 tenants.PaymentMethod.code', max_length=20, verbose_name='付款方式'),
        ),
    ]
