# Generated by Django 5.1.4 on 2026-05-23 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_alter_customer_options_and_more'),
        ('sales', '0009_alter_salesorderpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='member',
            field=models.ForeignKey(blank=True, help_text='服務對象/會員制度的歸屬;與 customer 不互斥(同行帶來的客戶可記在此)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_sales_orders', to='parties.customer', verbose_name='會員'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='這次交易的對象(收款/開發票對象);散客可不填', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='parties.customer', verbose_name='客戶'),
        ),
    ]
