# Generated by Django 5.1.4 on 2026-05-28 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_salesreturn'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='legacypurchase',
            new_name='sales_legac_member__6fc436_idx',
            old_name='sales_legac_member__1f8b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='legacypurchase',
            new_name='sales_legac_tenant__ae57da_idx',
            old_name='sales_legac_tenant__9d2a1e_idx',
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='doc_date',
            field=models.DateField(default=datetime.date.today, verbose_name='單據日期'),
        ),
    ]
