# Generated by Django 5.1.4 on 2026-10-03 23:39
"""銷貨 / 銷退明細存「未稅金額、稅額」,銷退明細存「沖回成本」;既有資料回填。

未稅 / 稅額:規則跟 apps/sales/services.py 的 split_tax_by_line 相同(這裡放一份凍結的副本,
之後改 services 不會改到這次回填的結果)。單頭不是「明細加總照稅別算出來的那個數」的單,
每行照稅別各自算、不補零頭,留給每日對帳列出來。

沖回成本:舊的銷退當初沒有算過成本,也沒有「什麼時候作廢」的紀錄,所以不是重播當時的存檔,
而是用一套固定的規則:序號 = 退回那幾台的進貨成本;配件 = 按數量比例,
**目前有效的**銷退照建立順序,把那一行退完的那一張拿餘數(有效銷退把一行全部退完時,
加總正好等於原行成本);作廢的銷退只按比例、不拿餘數。
"""
from decimal import Decimal

from django.db import migrations, models

CENTS = Decimal("0.01")
TAX_RATE = Decimal("0.05")


def _header(total, tax_method):
    if tax_method == "taxable_included":
        u = (total / (Decimal("1") + TAX_RATE)).quantize(CENTS)
        return u, (total.quantize(CENTS) - u).quantize(CENTS)
    if tax_method == "taxable_excluded":
        return total.quantize(CENTS), (total * TAX_RATE).quantize(CENTS)
    return total.quantize(CENTS), Decimal("0.00")


def _split(amounts, tax_method, subtotal, tax):
    header_ok = _header(sum(amounts, Decimal("0")), tax_method) == (subtotal, tax)
    lines = []
    for a in amounts:
        if tax_method == "taxable_included":
            u = (a / (Decimal("1") + TAX_RATE)).quantize(CENTS)
            t = a - u
        elif tax_method == "taxable_excluded":
            u = a
            t = (a * TAX_RATE).quantize(CENTS)
        else:
            u, t = a, Decimal("0.00")
        lines.append([u, t])
    if not lines:
        return lines
    du = subtotal - sum(u for u, _ in lines)
    dt = tax - sum(t for _, t in lines)
    if header_ok and abs(du) <= CENTS * len(lines) and abs(dt) <= CENTS * len(lines):
        k = max(range(len(lines)), key=lambda i: (abs(amounts[i]), -i))
        lines[k][0] += du
        lines[k][1] += dt
    return lines


def _fill_tax(item_model, fk, headers):
    """headers: {單頭 id: (稅別, 未稅小計, 稅額)}。明細照單頭分組,一次掃完。"""
    from itertools import groupby

    batch = []
    rows = item_model.objects.order_by(fk, "line_no", "id").iterator(chunk_size=2000)
    for header_id, group in groupby(rows, key=lambda it: getattr(it, fk)):
        items = list(group)
        tax_method, subtotal, tax = headers[header_id]
        for it, (u, t) in zip(items, _split([it.amount for it in items], tax_method, subtotal, tax)):
            it.untaxed_amount, it.tax_amount = u, t
            batch.append(it)
        if len(batch) >= 2000:
            item_model.objects.bulk_update(batch, ["untaxed_amount", "tax_amount"])
            batch = []
    if batch:
        item_model.objects.bulk_update(batch, ["untaxed_amount", "tax_amount"])


def backfill(apps, schema_editor):
    SalesOrder = apps.get_model("sales", "SalesOrder")
    SalesOrderItem = apps.get_model("sales", "SalesOrderItem")
    SalesReturn = apps.get_model("sales", "SalesReturn")
    SalesReturnItem = apps.get_model("sales", "SalesReturnItem")
    SalesReturnItemSerial = apps.get_model("sales", "SalesReturnItemSerial")

    _fill_tax(SalesOrderItem, "so_id", {
        pk: (method, subtotal, tax) for pk, method, subtotal, tax in
        SalesOrder.objects.values_list("id", "tax_method", "subtotal", "tax_amount")
    })
    _fill_tax(SalesReturnItem, "sr_id", {
        pk: (method, subtotal, tax) for pk, method, subtotal, tax in
        SalesReturn.objects.values_list("id", "original_so__tax_method", "subtotal", "tax_amount")
    })

    # 沖回成本:照建立順序,一筆原銷貨明細一筆一筆往下算(作廢的銷退不算進「先前已沖回」)
    serial_cost = {}
    for item_id, cost in SalesReturnItemSerial.objects.values_list(
        "item_id", "serial__purchase_unit_cost"
    ):
        serial_cost[item_id] = serial_cost.get(item_id, Decimal("0")) + (cost or Decimal("0"))
    prior = {}
    batch = []
    for it in SalesReturnItem.objects.select_related("product", "original_item", "sr").order_by("id"):
        oi = it.original_item
        if it.product.is_virtual:
            cost = Decimal("0.00")
        elif it.product.requires_serial:
            cost = serial_cost.get(it.id, Decimal("0")).quantize(CENTS)
        elif it.sr.is_void:
            cost = (oi.cost_at_post * it.qty / oi.qty).quantize(CENTS)
        else:
            done_qty, done_cost = prior.get(oi.id, (0, Decimal("0")))
            if done_qty + it.qty >= oi.qty:
                cost = (oi.cost_at_post - done_cost).quantize(CENTS)
            else:
                cost = (oi.cost_at_post * it.qty / oi.qty).quantize(CENTS)
            prior[oi.id] = (done_qty + it.qty, done_cost + cost)
        it.cost_at_post = cost
        batch.append(it)
    SalesReturnItem.objects.bulk_update(batch, ["cost_at_post"], batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_rename_sales_legac_member__1f8b3c_idx_sales_legac_member__6fc436_idx_and_more'),
        ('inventory', '0010_productserialidentifier'),
        ('catalog', '0027_category_needs_host_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='稅額'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='untaxed_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='未稅金額'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='cost_at_post',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='沖回成本'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='稅額'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='untaxed_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='未稅金額'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
