# Generated by Django 5.1.4 on 2026-10-06 08:32

from django.db import migrations, models

from apps.core.dates import add_months


def backfill(apps, schema_editor):
    """以前開的門號明細:把方案的綁約月數抄下來(之後方案改月數,舊的不跟著變)。
    沒作廢、有起算日的再補合約到期日 = 起算日(當時 = 開單日)+ 綁約月數。
    (中華電信的續約當時記的也是開單日,實際續約日比較晚的那幾筆要人事後改。)
    作廢的單不補到期日:到期提醒不該算到它。"""
    Item = apps.get_model("sales", "SalesOrderItem")
    rows = (
        Item.objects.filter(telecom_plan__isnull=False)
        .select_related("telecom_plan", "so")
    )
    changed = []
    for it in rows.iterator(chunk_size=500):
        it.contract_months = it.telecom_plan.contract_months
        if it.activation_date and not it.so.is_void:
            it.contract_end = add_months(it.activation_date, it.contract_months)
        changed.append(it)
    Item.objects.bulk_update(changed, ["contract_months", "contract_end"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_line_untaxed_tax_return_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='contract_end',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True, verbose_name='合約到期日'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='contract_months',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='綁約月數'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='prev_contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='原合約到期日'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
