# Generated by Django 5.1.4 on 2026-10-06 11:44

import apps.sales.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_category_needs_host_model'),
        ('parties', '0015_supplier_is_repair_vendor'),
        ('sales', '0017_contract_dates'),
        ('tenants', '0018_contract_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('status', models.CharField(blank=True, choices=[('contacted', '已聯絡'), ('declined', '不續約')], max_length=12, verbose_name='狀態')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
            ],
            options={
                'verbose_name': '合約聯絡紀錄',
                'verbose_name_plural': '合約聯絡紀錄',
            },
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(apps.sales.models.Digits('msisdn'), condition=models.Q(('telecom_plan__isnull', False)), name='soi_msisdn_digits'),
        ),
        migrations.AddField(
            model_name='contractfollowup',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='sales.salesorderitem', verbose_name='門號合約(銷貨明細)'),
        ),
        migrations.AddField(
            model_name='contractfollowup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶'),
        ),
        migrations.AddField(
            model_name='contractfollowup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='誰標的'),
        ),
    ]
