# Generated by Django 5.1.4 on 2026-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_contract_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='company_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='存檔時從方案抄過來;空的 = 當時沒有設定', max_digits=14, null=True, verbose_name='公司佣金'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='存檔時從方案抄過來(門市看的那一個)', max_digits=14, verbose_name='業務員佣金'),
        ),
    ]
