# Generated by Django 5.1.4 on 2026-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_company_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='staff_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='成交當下算好的(整行);空的 = 當時還沒有這個數字,看的時候用實際成本', max_digits=14, null=True, verbose_name='業務員成本'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='staff_cost_rule',
            field=models.CharField(blank=True, default='', editable=False, help_text='例 company:percent:20.00;空的 = 當時沒有規則,用的是實際成本', max_length=40, verbose_name='業務員成本當時的規則'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='staff_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True, verbose_name='沖回業務員成本'),
        ),
    ]
