# Generated by Django 5.1.4 on 2026-07-05 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0022_product_capacity_product_color_and_more'),
        ('inventory', '0009_alter_stockmovement_movement_type'),
        ('parties', '0015_supplier_is_repair_vendor'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('source', models.CharField(choices=[('manual_text', '手動貼單文字'), ('assistant', '指令助理'), ('ocr', '拍照 / PDF 辨識'), ('import', '檔案匯入')], default='manual_text', max_length=16, verbose_name='來源')),
                ('vendor_doc_no', models.CharField(blank=True, help_text='同廠商同單號不重複匯入(防重複入庫)', max_length=60, verbose_name='廠商出貨單號')),
                ('raw_text', models.TextField(blank=True, help_text='貼上的文字 / OCR 全文', verbose_name='原始內容')),
                ('status', models.CharField(choices=[('open', '待確認'), ('resolved', '已對應完(可過帳)'), ('committed', '已過帳'), ('cancelled', '已取消')], default='open', max_length=12, verbose_name='狀態')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('committed_purchase_order_id', models.BigIntegerField(blank=True, null=True, verbose_name='過帳後進貨單 ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_batches', to='parties.supplier', verbose_name='廠商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_batches', to='inventory.warehouse', verbose_name='入庫倉')),
            ],
            options={
                'verbose_name': '進貨待確認批次',
                'verbose_name_plural': '進貨待確認批次',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IntakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('line_no', models.PositiveIntegerField(verbose_name='行號')),
                ('raw_text', models.CharField(max_length=300, verbose_name='原始文字')),
                ('raw_barcode', models.CharField(blank=True, max_length=80, verbose_name='原始條碼')),
                ('raw_vendor_sku', models.CharField(blank=True, max_length=80, verbose_name='原始廠商料號')),
                ('raw_qty', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('raw_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='進價')),
                ('raw_serials', models.JSONField(blank=True, default=list, verbose_name='序號清單')),
                ('match_status', models.CharField(choices=[('auto_matched', '自動對應'), ('needs_review', '待選候選'), ('unknown', '未知商品'), ('conflict', '屬性衝突'), ('resolved', '已人工對應'), ('new_product', '已建新品對應'), ('rejected', '已駁回')], default='unknown', max_length=16, verbose_name='識別狀態')),
                ('match_confidence', models.PositiveIntegerField(default=0, help_text='0-100 整數;規則算出,非 AI 自評', verbose_name='信心分數')),
                ('candidates', models.JSONField(blank=True, default=list, help_text='[{product_id, sku, name, score, reason}] 給人選', verbose_name='候選清單')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='identity.intakebatch', verbose_name='批次')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_items', to='catalog.product', verbose_name='對應商品')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='處理者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '進貨待確認明細',
                'verbose_name_plural': '進貨待確認明細',
                'ordering': ['batch', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('kind', models.CharField(choices=[('barcode', '條碼(GTIN/EAN/UPC)'), ('vendor_sku', '廠商料號'), ('vendor_name', '廠商品名'), ('oem_model', '原廠型號'), ('legacy_name', '舊品名 / 簡稱')], max_length=16, verbose_name='類型')),
                ('value', models.CharField(max_length=200, verbose_name='原始字')),
                ('normalized_value', models.CharField(blank=True, db_index=True, help_text='value 正規化後的字,系統自動算,別名比對用', max_length=200, verbose_name='比對鍵')),
                ('verified', models.BooleanField(default=True, help_text='人工確認過的別名(從待確認區學來的都算);自動猜的可設 False', verbose_name='已確認')),
                ('source', models.CharField(choices=[('manual', '人工建立'), ('learned', '待確認區學來的'), ('imported', '匯入')], default='manual', max_length=12, verbose_name='來源')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product', verbose_name='對應商品')),
                ('supplier', models.ForeignKey(blank=True, help_text='留空 = 通用別名(我的舊品名 / 中文簡稱,不分廠商)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_aliases', to='parties.supplier', verbose_name='廠商')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '商品別名',
                'verbose_name_plural': '商品別名',
                'ordering': ['product', 'kind', 'value'],
            },
        ),
        migrations.AddIndex(
            model_name='intakebatch',
            index=models.Index(fields=['tenant', 'status'], name='identity_in_tenant__67ced0_idx'),
        ),
        migrations.AddConstraint(
            model_name='intakebatch',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('vendor_doc_no', ''), _negated=True), models.Q(('status', 'cancelled'), _negated=True)), fields=('tenant', 'supplier', 'vendor_doc_no'), name='uniq_intake_vendor_doc'),
        ),
        migrations.AddIndex(
            model_name='intakeitem',
            index=models.Index(fields=['tenant', 'match_status'], name='identity_in_tenant__297e70_idx'),
        ),
        migrations.AddConstraint(
            model_name='intakeitem',
            constraint=models.UniqueConstraint(fields=('batch', 'line_no'), name='uniq_intake_item_line'),
        ),
        migrations.AddIndex(
            model_name='productalias',
            index=models.Index(fields=['tenant', 'kind', 'normalized_value'], name='identity_pr_tenant__ead9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='productalias',
            index=models.Index(fields=['tenant', 'product'], name='identity_pr_tenant__70ad4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('kind', 'barcode')), fields=('tenant', 'normalized_value'), name='uniq_alias_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'supplier', 'kind', 'normalized_value'), name='uniq_alias_vendor_ref'),
        ),
    ]
