# Generated by Django 5.1.4 on 2026-07-06 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeitem',
            name='ocr_confidence',
            field=models.JSONField(blank=True, default=dict, help_text='拍照來源:每欄的辨識信心(0-1);與 match_confidence 是兩回事', verbose_name='OCR 辨識信心'),
        ),
        migrations.CreateModel(
            name='IntakeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('image', models.FileField(upload_to='intake_docs/%Y/%m/', verbose_name='原圖 / 檔案')),
                ('original_filename', models.CharField(blank=True, max_length=200, verbose_name='原始檔名')),
                ('ocr_status', models.CharField(choices=[('pending', '待辨識'), ('done', '已辨識'), ('failed', '辨識失敗')], default='pending', max_length=12, verbose_name='辨識狀態')),
                ('ocr_raw', models.JSONField(blank=True, default=dict, verbose_name='辨識原始結果')),
                ('ocr_message', models.CharField(blank=True, max_length=300, verbose_name='辨識訊息')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity.intakebatch', verbose_name='待確認批次')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '進貨單原圖',
                'verbose_name_plural': '進貨單原圖',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'ocr_status'], name='identity_in_tenant__f4532a_idx')],
            },
        ),
    ]
