# Generated by Django 5.1.4 on 2026-07-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_intakeitem_ocr_confidence_intakedocument'),
        ('purchasing', '0007_alter_purchaseorder_tax_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intakebatch',
            name='committed_purchase_order_id',
        ),
        migrations.AddField(
            model_name='intakebatch',
            name='committed_purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_batch', to='purchasing.purchaseorder', verbose_name='過帳後進貨單'),
        ),
        migrations.AddField(
            model_name='intakebatch',
            name='tax_method',
            field=models.CharField(choices=[('taxable_included', '應稅內含'), ('taxable_excluded', '應稅外加'), ('untaxed', '免稅')], default='taxable_included', help_text='過帳時帶入進貨單;不再一律寫死應稅內含', max_length=20, verbose_name='課稅別'),
        ),
        migrations.AddField(
            model_name='intakeitem',
            name='corrected_barcode',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='修正條碼'),
        ),
        migrations.AddField(
            model_name='intakeitem',
            name='corrected_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='修正品名'),
        ),
        migrations.AddField(
            model_name='intakeitem',
            name='corrected_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='修正數量'),
        ),
        migrations.AddField(
            model_name='intakeitem',
            name='corrected_serials',
            field=models.JSONField(blank=True, null=True, verbose_name='修正序號'),
        ),
        migrations.AddField(
            model_name='intakeitem',
            name='corrected_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='修正進價'),
        ),
        migrations.AddField(
            model_name='intakeitem',
            name='corrected_vendor_sku',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='修正料號'),
        ),
    ]
