# Generated by Django 5.1.4 on 2026-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_remove_intakebatch_committed_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakebatch',
            name='document_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='單據上印的總額;有填則過帳時與明細合計核對,差太多擋下', max_digits=14, null=True, verbose_name='單據總額'),
        ),
        migrations.AddField(
            model_name='intakedocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='檔案內容 sha256;同一單據已入庫過就擋下(可重傳救回失敗流程)', max_length=64, verbose_name='檔案雜湊'),
        ),
    ]
