# Generated by Django 5.1.4 on 2026-07-14 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_intakebatch_document_total_and_more'),
        ('tenants', '0014_add_repair_warranty_unlock_returnvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeReceivedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('unit_index', models.PositiveIntegerField(verbose_name='第幾台')),
                ('source', models.CharField(choices=[('document', '單據預填'), ('physical_scan', '實物掃描'), ('manual', '手動輸入')], default='manual', max_length=16, verbose_name='來源')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登記者')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_units', to='identity.intakeitem', verbose_name='待確認明細')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '實體收貨單位',
                'verbose_name_plural': '實體收貨單位',
                'ordering': ['item', 'unit_index'],
            },
        ),
        migrations.CreateModel(
            name='IntakeUnitIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('kind', models.CharField(choices=[('primary_serial', '主序號'), ('imei', 'IMEI'), ('imei2', 'IMEI2'), ('eid', 'EID'), ('sn', 'SN')], max_length=16, verbose_name='類型')),
                ('raw_value', models.CharField(max_length=80, verbose_name='原始值')),
                ('normalized_value', models.CharField(db_index=True, max_length=80, verbose_name='比對鍵')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主識別碼')),
                ('source', models.CharField(choices=[('document', '單據預填'), ('physical_scan', '實物掃描'), ('manual', '手動輸入')], default='manual', max_length=16, verbose_name='來源')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='identity.intakereceivedunit', verbose_name='實體單位')),
            ],
            options={
                'verbose_name': '實體單位識別碼',
                'verbose_name_plural': '實體單位識別碼',
                'ordering': ['unit', '-is_primary', 'kind'],
            },
        ),
        migrations.AddIndex(
            model_name='intakereceivedunit',
            index=models.Index(fields=['tenant', 'item'], name='identity_in_tenant__396f5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='intakereceivedunit',
            constraint=models.UniqueConstraint(fields=('item', 'unit_index'), name='uniq_intake_unit_index'),
        ),
        migrations.AddIndex(
            model_name='intakeunitidentifier',
            index=models.Index(fields=['tenant', 'normalized_value'], name='identity_in_tenant__15acfe_idx'),
        ),
    ]
