# Generated by Django 5.1.4 on 2026-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_intakereceivedunit_intakeunitidentifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalias',
            name='value',
            field=models.CharField(max_length=500, verbose_name='原始字'),
        ),
    ]
