# Generated by Django 5.1.4 on 2026-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_widen_alias_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeitem',
            name='alias_conflicts',
            field=models.JSONField(blank=True, default=list, help_text='[{"kind","label","value","product_sku"}, ...]', verbose_name='未學入的識別碼'),
        ),
    ]
