# Generated by Django 5.1.4 on 2026-10-02 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_supplier_product_and_style_code'),
        ('identity', '0008_alias_generic_unique_and_audit'),
        ('tenants', '0015_next_style_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDistinctDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('similar_products', models.JSONField(default=list, help_text='[{"id","sku","name"}, ...] 當下的快照,不跟著之後改名', verbose_name='當時相似的既有商品')),
                ('reason', models.CharField(max_length=200, verbose_name='哪裡不同')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='決定者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distinct_decisions', to='catalog.product', verbose_name='新建的商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '不同款決定',
                'verbose_name_plural': '不同款決定',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'product'], name='identity_pr_tenant__da8077_idx')],
            },
        ),
    ]
