# Generated by Django 5.1.4 on 2026-05-19 09:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_product_is_secondhand'),
        ('inventory', '0006_stockmovement_product_stockmovement_qty_and_more'),
        ('tenants', '0005_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('no', models.CharField(blank=True, editable=False, help_text='系統自動產生:TR-{6位流水}', max_length=30, verbose_name='單號')),
                ('doc_date', models.DateField(default=datetime.date.today, verbose_name='單據日期')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('is_void', models.BooleanField(default=False, verbose_name='作廢')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作業者')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_outs', to='inventory.warehouse', verbose_name='來源倉')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_ins', to='inventory.warehouse', verbose_name='目的倉')),
            ],
            options={
                'verbose_name': '調撥單',
                'verbose_name_plural': '調撥單',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行號')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='catalog.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.transferorder', verbose_name='調撥單')),
            ],
            options={
                'verbose_name': '調撥明細',
                'verbose_name_plural': '調撥明細',
                'ordering': ['to', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrderItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('line_pos', models.PositiveIntegerField(default=0, verbose_name='位序')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='transfers.transferorderitem', verbose_name='調撥明細')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_item_serials', to='inventory.productserial', verbose_name='序號')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='租戶')),
            ],
            options={
                'verbose_name': '調撥明細序號',
                'verbose_name_plural': '調撥明細序號',
                'ordering': ['item', 'line_pos', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='transferorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'no'), name='uniq_to_tenant_no'),
        ),
    ]
