# Generated by Django 5.1.4 on 2026-05-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認入庫時間'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='確認人'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='status',
            field=models.CharField(choices=[('dispatched', '派發中'), ('confirmed', '已完成')], default='dispatched', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='派發人'),
        ),
    ]
