# Generated by Django 5.1.4 on 2026-05-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transferorder_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorderitem',
            name='unit_cost_at_dispatch',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='配件用;派發當下從來源倉 balance.weighted_avg_cost 快照,確認時拿來算目的倉的加權平均', max_digits=14, verbose_name='派發時單台成本(未稅)'),
        ),
    ]
